#!/usr/bin/env python3
# PROVENANCE: the one-off extractor that produced web/js/planet/{context,terrain,materials,build,post,views,ui}.js
# and web/planet.html from reference/the-tower-planet-clean.html (Sueda's file) by slicing its lines.
# Every «a-b» marker below is replaced by the reference's lines a..b, byte for byte. A marker may carry
# asserted substitutions:  «1034» const wp= ⟹ let wp=   (the old text must occur exactly once in the slice).
# Everything else in the templates is structural wrapping or a documented hook (docs/planet.md).
# Re-running it OVERWRITES those files (planet.js, the API facade, is hand-written and not touched).
#   python3 tests/planet/extract.py
import os, re, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '../..'))
SRC = os.path.join(ROOT, 'reference/the-tower-planet-clean.html')
LINES = open(SRC, encoding='utf-8').read().split('\n')
MARK = re.compile(r'^«(\d+)(?:-(\d+))?»(.*)$')


def render(tpl):
    out = []
    for ln in tpl.split('\n'):
        m = MARK.match(ln)
        if not m:
            out.append(ln)
            continue
        a = int(m.group(1)); b = int(m.group(2) or a)
        text = '\n'.join(LINES[a - 1:b])
        for pair in [p for p in m.group(3).split(' ;; ') if p.strip()]:
            old, new = [s.strip() for s in pair.split('⟹')]
            n = text.count(old)
            if n != 1:
                sys.exit(f'«{a}-{b}»: expected 1 x {old!r}, found {n}')
            text = text.replace(old, new)
        out.append(text)
    return '\n'.join(out)


def write(rel, tpl):
    p = os.path.join(ROOT, rel)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, 'w', encoding='utf-8') as f:
        f.write(render(tpl).rstrip('\n') + '\n')
    print('wrote', rel)


# ------------------------------------------------------------------ context.js
write('web/js/planet/context.js', r'''// Tower Planet: the shared context. Generated by tests/planet/extract.py from reference/the-tower-planet-clean.html.
// Sueda's noise + helpers (verbatim, reference lines 105-123) are module exports so terrain.js can use them;
// createContext() makes her renderer, scene and camera (lines 102-103, 107-108, 215-226).
// `rand` = mulberry32(11) is kept on ctx for the record: the reference never draws from it, so there is no
// rand order to preserve. The clouds have their own mulberry32(197), inside build.js.
«105-106»
«109-123»
export { mulberry32, ihash, vnoise, fbm, smooth, lerp, col };

// Seam: `renderer` may be passed in (the reference always made its own); `canvas` is handed to
// WebGLRenderer when given; `fail` is her fail() from the page.
export function createContext({ canvas = null, renderer = null, fail = (msg) => console.error(msg) } = {}) {
«102-103»
«107-108»

«215-215»
  if (!renderer) {
«217-219» new THREE.WebGLRenderer(opts) ⟹ new THREE.WebGLRenderer(canvas?{...opts,canvas}:opts)
  }
«220-222»
  if (!renderer.domElement.isConnected)
«223-223»

«225-226»
  return { THREE, renderer, scene, camera, isMobile, reduceMotion, rand, R, fail };
}
''')

# ------------------------------------------------------------------ terrain.js
write('web/js/planet/terrain.js', r'''// Tower Planet terrain. Generated by tests/planet/extract.py from reference/the-tower-planet-clean.html.
// Above the line: Sueda's flat design space, the road and the height field, verbatim (reference lines 125-213).
// Below the line: the surface API the game uses to live on the sphere (new code, docs/planet.md).
// Needs the global THREE (the road curve is a THREE.CatmullRomCurve3).
import { vnoise, fbm, smooth, lerp } from './context.js';

«125-213»

export { C, RP, TOWER_BASE, TOWER_H, TOWER_ROT, mapFlat, pathPts, curve, PS, PB, pathDist,
  Hland, Hfar, landMask, heightCore, H, prof, cragR };

/* ================= the surface API (new; everything above is hers) ================= */
// Flat design space: x east, z south (the tower's crag C sits on the planet's +Y pole), y = altitude.
// mapFlat wraps it onto the sphere (azimuthal equidistant round C): 1 flat unit = 1 world unit along the ground.
const _p = new THREE.Vector3(), _q = new THREE.Vector3(), _e = new THREE.Vector3(), _s = new THREE.Vector3(), _n = new THREE.Vector3();
const _m = new THREE.Matrix4(), _qy = new THREE.Quaternion(), _Y = new THREE.Vector3(0, 1, 0);
export const MAX_RELIEF = 90;          // the terrain never rises above RP + 90 (the tower and crag are meshes)
export const CRAG_FOOT = 50;           // flat distance from C inside which the crag stands (prof[0] = 48)

// H(fx, fz): < 0 is water (its depth); the planet mesh draws max(h, 0), so the sea surface is at altitude 0
export function heightAtFlat(fx, fz) { return H(fx, fz); }
export function groundAtFlat(fx, fz) { return Math.max(0, H(fx, fz)); }
export function isWaterFlat(fx, fz) { return H(fx, fz) < 0; }
export function onCragFlat(fx, fz) { return Math.hypot(fx - C.x, fz - C.z) < CRAG_FOOT; }

export function flatToWorld(fx, y, fz, out = new THREE.Vector3()) { return mapFlat(fx, y, fz, out); }
// a point on the drawn ground (water at 0), lifted by `lift`
export function surfaceToWorld(fx, fz, lift = 0, out = new THREE.Vector3()) { return mapFlat(fx, groundAtFlat(fx, fz) + lift, fz, out); }
// the exact inverse of mapFlat (for points less than half a turn from C): -> { x, y, z } with y = altitude
export function worldToFlat(p, out = {}) {
  const r = Math.hypot(p.x, p.y, p.z), s = Math.hypot(p.x, p.z), th = Math.atan2(s, p.y), d = th * RP;
  const ux = s > 1e-12 ? p.x / s : 0, uz = s > 1e-12 ? p.z / s : 1;
  out.x = C.x + ux * d; out.y = r - RP; out.z = C.z + uz * d;
  return out;
}
// the radial up at a flat point (what upright things stand along)
export function upAtFlat(fx, fz, out = new THREE.Vector3()) { return mapFlat(fx, 0, fz, out).normalize(); }
// the drawn ground's normal (world space), by central differences on the wrapped surface
export function normalAtFlat(fx, fz, out = new THREE.Vector3(), e = 0.5) {
  surfaceToWorld(fx + e, fz, 0, _e).sub(surfaceToWorld(fx - e, fz, 0, _p));
  surfaceToWorld(fx, fz + e, 0, _s).sub(surfaceToWorld(fx, fz - e, 0, _q));
  return out.crossVectors(_s, _e).normalize();
}
// the local frame at a flat point: up = radial, east = flat +x, south = flat +z, orthonormal (right-handed:
// east, up, south = local x, y, z). position = the drawn ground + lift; quaternion turns an object built
// upright in flat space (y up, +x east, +z south) onto the planet; `yaw` = its rotation.y in flat space.
export function frameAt(fx, fz, { lift = 0, yaw = 0 } = {}) {
  const h = H(fx, fz), g = Math.max(0, h);
  const position = mapFlat(fx, g + lift, fz, new THREE.Vector3());
  const up = position.clone().normalize();
  const east = mapFlat(fx + 0.5, g, fz, new THREE.Vector3()).sub(mapFlat(fx - 0.5, g, fz, _p));
  east.addScaledVector(up, -east.dot(up)).normalize();
  const south = new THREE.Vector3().crossVectors(east, up).normalize();
  east.crossVectors(up, south);
  const quaternion = new THREE.Quaternion().setFromRotationMatrix(_m.makeBasis(east, up, south));
  if (yaw) quaternion.multiply(_qy.setFromAxisAngle(_Y, yaw));
  return { position, quaternion, up, east, south, height: h, ground: g, water: h < 0 };
}
export function placeOnSurface(obj, fx, fz, opts = {}) {
  const f = frameAt(fx, fz, opts);
  obj.position.copy(f.position); obj.quaternion.copy(f.quaternion);
  return f;
}
// her baking step for one geometry built in flat space (y up, ground at H): every vertex goes through mapFlat
// (reference lines 597-604). For decals that must follow the ground (fields, roads, marks) build them at H + a lift.
export function wrapFlatGeometry(geo, matrix = null) {
  if (matrix) geo.applyMatrix4(matrix);
  const p = geo.attributes.position;
  for (let i = 0; i < p.count; i++) { mapFlat(p.getX(i), p.getY(i), p.getZ(i), _n); p.setXYZ(i, _n.x, _n.y, _n.z); }
  p.needsUpdate = true; geo.computeVertexNormals(); geo.computeBoundingSphere();
  return geo;
}
// ray -> the drawn ground (march + bisection on the altitude gap). origin / dir in world space, dir unit.
// -> { fx, fz, world, height, onWater, t } | null
export function raycastSurface(origin, dir, maxAlt = MAX_RELIEF) {
  const R1 = RP + maxAlt, b = origin.dot(dir), c = origin.lengthSq() - R1 * R1, disc = b * b - c;
  if (disc < 0) return null;
  const sq = Math.sqrt(disc), tEnd = -b + sq;
  if (tEnd < 0) return null;
  const q = {};
  const gap = t => { _p.copy(origin).addScaledVector(dir, t); worldToFlat(_p, q); return q.y - Math.max(0, H(q.x, q.z)); };
  let t0 = Math.max(0, -b - sq), g0 = gap(t0), t1 = t0, hit = g0 <= 0;
  for (let i = 0; i < 4000 && !hit && t1 < tEnd; i++) {
    t1 = t0 + Math.max(0.2, g0 * 0.5);
    const g1 = gap(t1);
    if (g1 <= 0) { hit = true; break; }
    t0 = t1; g0 = g1;
  }
  if (!hit) return null;
  for (let i = 0; i < 28; i++) { const tm = (t0 + t1) / 2; if (gap(tm) > 0) t0 = tm; else t1 = tm; }
  const world = origin.clone().addScaledVector(dir, t1);
  worldToFlat(world, q);
  const height = H(q.x, q.z);
  return { fx: q.x, fz: q.z, world, height, onWater: height < 0, t: t1 };
}
''')

# ------------------------------------------------------------------ materials.js
write('web/js/planet/materials.js', r'''// Tower Planet materials. Generated by tests/planet/extract.py from reference/the-tower-planet-clean.html.
// Her toon material, GLSL chunks, palette uniforms (lines 227-332) and colours (991-1005), verbatim.
«239-246»
«269-331»
«991-992»
export { GLSL_COMMON, STONE_FRAG, ROCK_FRAG, GROUND_FRAG, COLOUR_KEYS, DEFAULT_COLOURS };

// her uniforms + the toon factory, made per planet (in the reference they sat in the closure)
export function createMaterials(ctx) {
«227-237»
«247-268»
  return { uTime, SUN, BG, DAYLIGHT, PALU, gradTex, toon };
}

// her colour model (lines 993-1005). The DOM half (pickers, --bg / --hint) moved to ui.js, behind `emit`.
export function createColours(ctx, emit = () => {}) {
  const { BG, PALU } = ctx;
  const current = {};
«993-993»
«995-997»
  UNI[k].value.set(hex);current[k]=hex;
«1004-1004»
  emit(k,hex);
«1005-1005»
  for(const [k] of COLOUR_KEYS) setColour(k,DEFAULT_COLOURS[k]);
  return { UNI, warmTint, setColour, getColours: () => ({ ...current }) };
}
''')

# ------------------------------------------------------------------ build.js
write('web/js/planet/build.js', r'''// Tower Planet world. Generated by tests/planet/extract.py from reference/the-tower-planet-clean.html.
// Her build(), verbatim (reference lines 333-685): space sky with DAYLIGHT, atmosphere, the planet mesh
// (land, sea, coast), the road, crag, arcades, helix ramp, terrace + tower (built flat, wrapped by mapFlat),
// the six clouds and the sun. Construction order is part of the look (material / object ids decide draw ties).
import { mulberry32, vnoise, fbm, smooth, lerp, col } from './context.js';
import { C, RP, TOWER_BASE, TOWER_H, TOWER_ROT, mapFlat, curve, H, heightCore, cragR } from './terrain.js';
import { STONE_FRAG, ROCK_FRAG, GROUND_FRAG } from './materials.js';

«333-333»
export function build(ctx){
  const { scene, renderer, isMobile, SUN, BG, DAYLIGHT, PALU, toon } = ctx;
«335-685»
''')

# ------------------------------------------------------------------ post.js
write('web/js/planet/post.js', r'''// Tower Planet post. Generated by tests/planet/extract.py from reference/the-tower-planet-clean.html.
// Her Red Arch gouache pass (Kuwahara, edges, pencil line), the lens + grain + gouache finish, the render
// targets and renderFinish, verbatim (reference lines 687-911). renderFinish reads the world from ctx.world.
export function createPost(ctx){
  const { renderer, scene, camera } = ctx;
«687-897»
  const world=ctx.world;
«898-911»
  return {
    post, kuwaharaMat, edgeMat, paintLineMat, paintNormalMat, postScene, postCam, postQuad,
    paintPass, makeRT, renderFinish,
    get rt(){ return rt; },
    get targets(){ return { rt, rtPaint, rtPaintNormal, rtPaintEdge, rtPaintLine }; }
  };
}
''')

# ------------------------------------------------------------------ views.js
write('web/js/planet/views.js', r'''// Tower Planet views. Generated by tests/planet/extract.py from reference/the-tower-planet-clean.html.
// Hers, verbatim: the orbit and road-walk cameras, computeFit / resize, drag / pinch / wheel input, the style
// state and the loop body with uBlend + DAYLIGHT by altitude (reference lines 913-957, 967-989, 1016-1092).
// New (documented hooks, docs/planet.md): mode 'local' (a camera over any flat point: cameraLocal) and mode
// 'path' (a flight from wherever the camera is down to a local view: descendTo), blend / daylight overrides,
// render hooks, pick and toScreen through her lens. In 'orbit' and 'walk' every line runs as in the reference.
import { smooth, lerp } from './context.js';
import { C, RP, TOWER_BASE, mapFlat, curve, H, worldToFlat, raycastSurface } from './terrain.js';

export function createViews(ctx, P, { input = true, emit = () => {} } = {}) {
  const { renderer, scene, camera, isMobile, reduceMotion, uTime, SUN, DAYLIGHT } = ctx;
  const { post, makeRT, renderFinish } = P;
«913-934»

«936-940»
  if (input) {
«941-957»
  }

  // her setWalking / toWalk / toOrbit (959-962); their DOM halves moved to ui.js (emit)
  function setWalking(v){walking=v;emit('walking',v);}
  function toWalk(){followDescent=true;mode='walk';cancelPath();emit('mode',mode);setWalking(true);}
  function toOrbit(){followDescent=true;mode='orbit';cancelPath();emit('mode',mode);setWalking(false);yawT=pitchT=0;}

«967-968»
  function markStyle(){
«971-973»
    emit('style',selected);
  }
«979-979»
«989-989»

«1016-1022»

  /* ---------------- new: local + path cameras, overrides, hooks ---------------- */
  let daylightOverride=null, localFov=50, pathFov=50, path=null;
  const local={fx:C.x, fz:0, dist:70, pitch:1.0, yaw:0, snap:false};
  const free={pos:new THREE.Vector3(0,RP*4,0), look:new THREE.Vector3(), up:new THREE.Vector3(0,0,-1), snap:false};
  const hooks={beforeRender:[], beforeFinish:[], afterFinish:[]};
  const _n=new THREE.Vector3(), _e=new THREE.Vector3(), _s=new THREE.Vector3(), _h=new THREE.Vector3(), _p=new THREE.Vector3();
  const pPos=new THREE.Vector3(), pLook=new THREE.Vector3(), pUp=new THREE.Vector3(), d0=new THREE.Vector3(), d1=new THREE.Vector3();
  const focus={fx:C.x, fz:0};
  const ground=(fx,fz)=>Math.max(0,H(fx,fz));
  const wrapAngle=a=>Math.atan2(Math.sin(a),Math.cos(a));
  // the local frame at a flat point: N radial up, E flat +x, S flat +z
  function frameVecs(fx,fz,y){
    mapFlat(fx,y,fz,_n).normalize();
    mapFlat(fx+.5,y,fz,_e).sub(mapFlat(fx-.5,y,fz,_p));
    _e.addScaledVector(_n,-_e.dot(_n)).normalize(); _s.crossVectors(_e,_n);
  }
  // a camera `dist` from the ground point (fx, fz), `pitch` above its horizon (pi/2 = straight down), on the
  // flat bearing `yaw` (0 = south of the point, looking north; +yaw swings it east). Up = the true camera up,
  // so a top-down view stays well defined. Never under the ground.
  function poseAt(fx,fz,dist,pitch,yaw,pos,look,up){
    const gy=ground(fx,fz);
    mapFlat(fx,gy,fz,look); frameVecs(fx,fz,gy);
    _h.copy(_e).multiplyScalar(Math.sin(yaw)).addScaledVector(_s,Math.cos(yaw));
    const cp=Math.cos(pitch), sp=Math.sin(pitch);
    pos.copy(look).addScaledVector(_h,dist*cp).addScaledVector(_n,dist*sp);
    up.copy(_n).multiplyScalar(cp).addScaledVector(_h,-sp).normalize();
    const q=worldToFlat(pos), floor=ground(q.x,q.z)+2.5;
    if(q.y<floor) mapFlat(q.x,floor,q.z,pos);
    focus.fx=fx; focus.fz=fz;
    return gy;
  }
  function cancelPath(){ if(path){ const p=path; path=null; p.resolve(false); } }
  // the start of a flight: the local view we are in, or (from orbit / walk) straight down over the point
  // under the camera, turned so the screen's up does not change
  function poseFromCamera(){
    if(mode==='local') return {...local};
    const f=worldToFlat(camPos), g=ground(f.x,f.z);
    frameVecs(f.x,f.z,g);
    _h.copy(camUp).addScaledVector(_n,-camUp.dot(_n));
    if(_h.lengthSq()<1e-8) _h.copy(_s).negate();
    _h.normalize().negate();
    return {fx:f.x, fz:f.z, dist:Math.max(1,camPos.length()-RP-g), pitch:Math.PI/2, yaw:Math.atan2(_h.dot(_e),_h.dot(_s))};
  }
  function placePath(now){
    const p=path;
    if(p.t0===null) p.t0=now;
    const s=Math.min(1,(now-p.t0)/p.ms);
    const a=p.from, b=p.to;
    // the focus slides across the globe early, the height falls on a log scale, the view stays top-down
    // until the last stretch, then tips into the target pitch
    const ef=smooth(0,.62,s), ed=smooth(.04,1,s);
    _p.copy(d0).lerp(d1,ef); if(p.arc>1e-6){ _p.copy(d0).multiplyScalar(Math.sin((1-ef)*p.arc)).addScaledVector(d1,Math.sin(ef*p.arc)).divideScalar(Math.sin(p.arc)); }
    const f=worldToFlat(_p.multiplyScalar(RP));
    const hop=Math.max(0,p.arc*RP*.55-Math.max(a.dist,b.dist))*Math.sin(Math.PI*Math.min(1,s/.8));
    const dist=Math.exp(lerp(Math.log(a.dist),Math.log(b.dist),ed))+hop;
    const pitch=lerp(lerp(a.pitch,Math.PI/2,smooth(0,.25,s)),b.pitch,smooth(.58,1,s));
    const yaw=a.yaw+wrapAngle(b.yaw-a.yaw)*smooth(.12,.9,s);
    pathFov=lerp(p.fov0,localFov,smooth(.3,1,s));   // the lens widens as we come down, not before
    poseAt(f.x,f.z,dist,pitch,yaw,dPos,dLook,dUp);
    // ease out of the camera we started from
    const w=smooth(0,.3,s);
    dPos.lerp(p.P0,1-w); dLook.lerp(p.L0,1-w); dUp.lerp(p.U0,1-w).normalize();
    if(s>=1){
      Object.assign(local,b); mode='local'; path=null; emit('mode',mode); p.resolve(true);
    }
  }
  function descendTo(o={}){
    cancelPath();
    const a=poseFromCamera();
    const pitch=o.pitch??1.05;
    const dist=o.dist??(o.alt!=null?o.alt/Math.max(.2,Math.sin(pitch)):70);
    const b={fx:o.fx??local.fx, fz:o.fz??local.fz, dist, pitch, yaw:o.yaw??local.yaw};
    if(o.fov!=null) localFov=o.fov;
    if(walking) setWalking(false);
    mapFlat(a.fx,0,a.fz,d0).normalize(); mapFlat(b.fx,0,b.fz,d1).normalize();
    return new Promise(resolve=>{
      path={from:a, to:b, ms:Math.max(1,o.ms??5200), t0:null, arc:Math.acos(Math.max(-1,Math.min(1,d0.dot(d1)))),
        P0:camPos.clone(), L0:camLook.clone(), U0:camUp.clone(), fov0:camera.fov, resolve};
      mode='path'; emit('mode',mode);
    });
  }
  // a camera the host places itself (the voyage to the Moon, cut scenes): world-space position / look / up.
  // Her smoothing still applies unless snap; blend + daylight still follow the altitude.
  function cameraFree(o={}){
    cancelPath();
    if(o.position) free.pos.copy(o.position); if(o.look) free.look.copy(o.look); if(o.up) free.up.copy(o.up);
    if(o.fov!=null) localFov=o.fov;
    free.snap=!!o.snap;
    if(walking) setWalking(false);
    if(mode!=='free'){ mode='free'; emit('mode',mode); }
  }
  function cameraLocal(o={}){
    cancelPath();
    for(const k of ['fx','fz','dist','pitch','yaw']) if(o[k]!=null) local[k]=o[k];
    if(o.fov!=null) localFov=o.fov;
    local.snap=!!o.snap;
    if(walking) setWalking(false);
    if(mode!=='local'){ mode='local'; emit('mode',mode); }
    return {...local};
  }

  // her frame() body (lines 1024-1092): the loop itself (requestAnimationFrame) lives in planet.js
  function frame(now){
«1025-1033»
«1034-1034» const wp= ⟹ let wp=
«1035-1041»
  } else if(mode==='local'||mode==='path'||mode==='free'){
    if(mode==='free'){ dPos.copy(free.pos); dLook.copy(free.look); dUp.copy(free.up).normalize(); const q=worldToFlat(free.look); focus.fx=q.x; focus.fz=q.z; if(free.snap){ snap=true; free.snap=false; } }
    if(mode==='path') placePath(now);
    if(mode==='local'){ poseAt(local.fx,local.fz,local.dist,local.pitch,local.yaw,dPos,dLook,dUp); if(local.snap){ snap=true; local.snap=false; } }
    else if(mode==='path') snap=true;
    wy=ground(focus.fx,focus.fz); mapFlat(focus.fx,wy,focus.fz,wW);
«1042-1055»
«1056-1056» mode==='orbit'?40:68 ⟹ mode==='orbit'?40:mode==='walk'?68:mode==='path'?pathFov:localFov
«1057-1067»
«1068-1068» wide=(mode==='orbit') ⟹ wide=(mode==='orbit'||((mode==='path'||mode==='free')&&camPos.length()-RP>220))
«1069-1081»
  if(daylightOverride!==null) DAYLIGHT.value=daylightOverride;
«1082-1090»
  for(const fn of hooks.beforeRender) fn(dt,now);
  const rt=P.rt;
«1091-1091»
  for(const fn of hooks.beforeFinish) fn(dt,now);
«1092-1092»
  for(const fn of hooks.afterFinish) fn(dt,now);
  }

  /* ---------------- pick / toScreen through her lens (post: fish, uFish) ---------------- */
  const ray=new THREE.Raycaster(), ndc=new THREE.Vector2();
  function fishUV(x,y){
    const o=post.uniforms.uOut.value, a=o.x/o.y, F=post.uniforms.uFish.value;
    let px=(x-.5)*a, py=y-.5; const k=1/(1+F*(px*px+py*py)); px*=k; py*=k;
    return [px/a+.5, py+.5];
  }
  // screen point -> the planet's ground under it: { fx, fz, world, height, onWater } | null
  function pick(clientX,clientY){
    const r=renderer.domElement.getBoundingClientRect();
    const [sx,sy]=fishUV((clientX-r.left)/r.width,1-(clientY-r.top)/r.height);
    ndc.set(sx*2-1,sy*2-1); ray.setFromCamera(ndc,camera);
    return raycastSurface(ray.ray.origin,ray.ray.direction);
  }
  // world point -> client pixels on the lensed screen: { x, y, behind }
  function toScreen(v){
    _p.copy(v).project(camera);
    const tx=(_p.x+1)/2, ty=(_p.y+1)/2; let x=tx, y=ty;
    for(let i=0;i<12;i++){ const [fx,fy]=fishUV(x,y); x+=tx-fx; y+=ty-fy; }
    const r=renderer.domElement.getBoundingClientRect();
    return { x:r.left+x*r.width, y:r.top+(1-y)*r.height, behind:_p.z>1 };
  }

  return {
    frame, resize, computeFit, pick, toScreen, hooks,
    prime(t){ last=t; }, setWorld(w){ world=w; }, markStarted(){ started=true; },
    walk:toWalk, orbit:toOrbit, setWalking, descendTo, cameraLocal, cameraFree,
    setBlend:selectStyle,
    autoBlend(on=true){ followDescent=!!on; if(on) markStyle(); },
    setDaylight(v){ daylightOverride=v; },
    autoDaylight(on=true){ daylightOverride=on?null:DAYLIGHT.value; },
    orbitSpin(on=true){ lastInteract=on?-1e9:Infinity; },
    setOrbit(o={}){ if(o.az!=null) orbitAz=o.az; if(o.el!=null) orbitEl=o.el; if(o.dist!=null) orbitDist=o.dist; },
    get mode(){ return mode; }, get walking(){ return walking; }, get styleSelected(){ return activeStyle; },
    get followDescent(){ return followDescent; }, get local(){ return {...local}; }, get focus(){ return {...focus}; },
    get altitude(){ return Math.max(0,camera.position.length()-RP); },
    state(){ return { mode, walking, blend:post.uniforms.uBlend.value, daylight:DAYLIGHT.value, followDescent,
      daylightOverride, altitude:Math.max(0,camera.position.length()-RP), orbit:{az:orbitAz, el:orbitEl, dist:orbitDist, fitDist},
      local:{...local}, focus:{...focus}, fov:camera.fov, path:path?{from:path.from, to:path.to, ms:path.ms}:null }; }
  };
}
''')

# ------------------------------------------------------------------ ui.js
write('web/js/planet/ui.js', r'''// Tower Planet chrome. Generated by tests/planet/extract.py from reference/the-tower-planet-clean.html.
// Her DOM controls (reference lines 959-1014): Walk the road / Back to orbit, Grain / Gouache, Colours, Space, Esc.
// The markup and CSS are hers, verbatim, in web/planet.html; this binds them to a planet (createPlanet).
// The game does not mount it (ART_DIRECTION §3).
import { COLOUR_KEYS, DEFAULT_COLOURS } from './materials.js';

export function mountPlanetUI(planet) {
«959-959»
  planet.on('walking',v=>{walkBtn.setAttribute('aria-pressed',v);walkBtn.textContent=v?'Pause':(planet.mode==='walk'?'Keep walking':'Walk the road');});
  planet.on('mode',m=>{
    if(m==='walk'){backBtn.hidden=false;hint.textContent='Drag to look around';}
    else if(m==='orbit'){backBtn.hidden=true;hint.textContent='Drag to spin, scroll or pinch to zoom';}
    else backBtn.hidden=false;
  });
  const toWalk=planet.walk, toOrbit=planet.orbit, setWalking=planet.setWalking;
  walkBtn.addEventListener('click',()=>{ if(planet.mode==='orbit') toWalk(); else setWalking(!planet.walking); });
«964-965»

  const selectStyle=v=>planet.setBlend(v);
«969-969»
  function markStyle(selected){
«974-977»
  }
  planet.on('style',markStyle); markStyle(planet.styleSelected);
«980-988»

  const UNI=planet.colourUniforms;
«994-994»
  planet.on('colour',({k,hex})=>{
    if(pickers[k]) pickers[k].value=hex;
«999-1003»
  });
  const setColour=(k,hex)=>planet.setColour(k,hex);
«1006-1011» setColour(k,DEFAULT_COLOURS[k]) ⟹ setColour(k,planet.getColours()[k])
«1012-1014»
  return { walkBtn, backBtn, hint, styleButtons, pickers, colBtn, colPanel };
}
''')

# ------------------------------------------------------------------ planet.html
write('web/planet.html', r'''«1-86»
<script src="vendor/three.min.js"></script>
<script type="module">
// The Tower Planet, rebuilt only from web/js/planet/* (tests/planet/fidelity.mjs checks it against
// reference/the-tower-planet-clean.html pixel for pixel). Her markup and CSS above are byte-identical.
import { createPlanet } from './js/planet/planet.js';
import { mountPlanetUI } from './js/planet/ui.js';
«97-100»

«1096-1096»
  let planet;
  try{ planet=createPlanet({ fail, onFirstFrame:()=>{
«1101-1102»
  } }); }catch(e){ console.error(e); fail('The scene failed to build: '+(e&&e.message||e)); return; }
  if(!planet) return;
  mountPlanetUI(planet);
  window.__planet=planet;
«1104-1108»
''')
