import puppeteer from 'puppeteer-core';
const b = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', args: ['--use-angle=metal', '--window-size=1440,900'], defaultViewport: { width: 1440, height: 900 } });
const page = await b.newPage(); const errs = [];
page.on('pageerror', e => { errs.push(e.message); console.log('[pageerror]', e.message); });
page.on('console', m => { if (m.type() === 'error') console.log('[console.error]', m.text().slice(0, 200)); });
const sleep = ms => new Promise(r => setTimeout(r, ms));
const OUT = '/Users/suedagul/agora/shots/look-lab/';
await page.goto('http://localhost:8893/look.html', { waitUntil: 'load' });
await page.waitForFunction(() => window.__look, { timeout: 90000 }); await sleep(3000);
await page.screenshot({ path: OUT + '10-standalone-map.png' });
await page.evaluate(() => document.querySelector('.ll-stage').click());
await page.waitForFunction(() => window.__look.stages.scene === 'globe', { timeout: 60000 }); await sleep(3500);
await page.screenshot({ path: OUT + '11-standalone-globe.png' });
console.log(await page.evaluate(() => ({ target: __look.look.lab.target, probe: document.querySelector('.ll-probe').textContent, gG: { ...__look.globe.painter.G }, G: { ...__look.painter.G } })));
await page.evaluate(() => { const i = document.querySelector('#g-saturation'); i.value = 1.45; i.dispatchEvent(new Event('input', { bubbles: true })); });
await sleep(1500);
console.log('globe sat after', await page.evaluate(() => __look.globe.painter.G.saturation));
await page.screenshot({ path: OUT + '12-standalone-globe-sat.png' });
console.log('errors', errs.length);
await b.close();
