// Tower Planet world. Generated by tests/planet/extract.py from reference/the-tower-planet-clean.html.
// Her build(), verbatim (reference lines 333-685): space sky with DAYLIGHT, atmosphere, the planet mesh
// (land, sea, coast), the road, crag, arcades, helix ramp, terrace + tower (built flat, wrapped by mapFlat),
// the six clouds and the sun. Construction order is part of the look (material / object ids decide draw ties).
import { mulberry32, vnoise, fbm, smooth, lerp, col } from './context.js';
import { C, RP, TOWER_BASE, TOWER_H, TOWER_ROT, mapFlat, curve, H, heightCore, cragR } from './terrain.js';
import { STONE_FRAG, ROCK_FRAG, GROUND_FRAG } from './materials.js';

/* ---------------- build ---------------- */
export function build(ctx){
  const { scene, renderer, isMobile, SUN, BG, DAYLIGHT, PALU, toon } = ctx;
  const world = {};
  const v3=new THREE.Vector3(), m4=new THREE.Matrix4(), q=new THREE.Quaternion(), s3=new THREE.Vector3(), Y=new THREE.Vector3(0,1,0);

  /* space: radical ultramarine, a touch brighter around the planet */
  const sky = new THREE.Mesh(new THREE.SphereGeometry(6000,32,16), new THREE.ShaderMaterial({
    side:THREE.BackSide, depthWrite:true, fog:false, uniforms:{uBg:BG,uGlow:PALU.uGlow,uDaylight:DAYLIGHT,uSunDirection:{value:SUN}},
    vertexShader:`varying vec3 vDir; void main(){ vDir=position; gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,
    fragmentShader:`uniform vec3 uBg,uGlow,uSunDirection; uniform float uDaylight; varying vec3 vDir;
      float h3(vec3 p){ p=fract(p*0.3183099+0.1); p*=17.0; return fract(p.x*p.y*p.z*(p.x+p.y+p.z)); }
      float skyNoise(vec2 p){
        vec2 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);
        return mix(mix(h3(vec3(i,7.0)),h3(vec3(i+vec2(1,0),7.0)),f.x),mix(h3(vec3(i+vec2(0,1),7.0)),h3(vec3(i+vec2(1,1),7.0)),f.x),f.y);
      }
      vec3 starLayer(vec2 uv,vec2 grid,float density,float radius,float brightness,float seed){
        vec2 p=uv*grid,id=floor(p);
        float pick=h3(vec3(id,seed));
        vec2 centre=vec2(h3(vec3(id,seed+11.0)),h3(vec3(id,seed+27.0)))*0.6+0.2;
        vec2 f=fract(p)-centre;float r=length(f);
        float core=1.0-smoothstep(radius*0.32,radius,r);
        float halo=exp(-r*r/(radius*radius*4.0))*0.12;
        float glint=0.0;
        if(seed>30.0){
          glint=(exp(-abs(f.x)*110.0)*exp(-abs(f.y)*9.0)+exp(-abs(f.y)*110.0)*exp(-abs(f.x)*9.0))*0.16;
        }
        vec3 tint=mix(vec3(0.70,0.83,1.0),vec3(1.0,0.88,0.65),h3(vec3(id,seed+63.0)));
        return tint*(core+halo+glint)*brightness*(0.45+0.55*pick)*step(1.0-density,pick);
      }
      void main(){ vec3 d=normalize(vDir);
        float k=dot(d,normalize(-cameraPosition));
        float al=asin(min(1.0,${RP.toFixed(1)}/length(cameraPosition)));
        float glow=smoothstep(cos(min(al*1.7,3.1)),cos(al),k);
        float lum=dot(uBg,vec3(0.299,0.587,0.114));
        vec3 glowC=mix(uGlow*0.6, mix(uBg*1.35+0.03,uGlow,0.35), smoothstep(0.05,0.3,lum));
        vec3 c=mix(uBg,glowC,glow*0.75);
        // A deep field of fine dust, small stars and a few brighter beacons.
        vec2 skyUV=vec2(atan(d.z,d.x)/6.2831853+0.5,asin(clamp(d.y,-1.0,1.0))/3.14159265+0.5);
        float night=1.0-smoothstep(0.10,0.36,lum);
        float band=pow(max(0.0,1.0-abs(dot(d,normalize(vec3(.48,.74,-.47))))/.32),2.0);
        float dust=0.56*skyNoise(skyUV*vec2(28,14))+0.29*skyNoise(skyUV*vec2(76,38))+0.15*skyNoise(skyUV*vec2(190,95));
        c+=mix(vec3(.045,.067,.15),vec3(.105,.071,.14),dust)*band*dust*night;
        vec3 stars=starLayer(skyUV,vec2(1600,800),.027,.21,.64,3.0);
        stars+=starLayer(skyUV,vec2(520,260),.039,.13,1.04,19.0);
        stars+=starLayer(skyUV,vec2(130,65),.022,.070,1.25,43.0);
        c+=stars*night*(1.0-glow*.48);
        // The same painted sky becomes daylight as we descend into the atmosphere.
        vec3 localUp=normalize(cameraPosition);
        float elevation=clamp(dot(d,localUp),0.0,1.0);
        float haze=pow(1.0-elevation,2.6);
        vec3 daySky=mix(vec3(0.15,0.42,0.72),vec3(0.72,0.85,0.92),haze);
        float sunward=max(0.0,dot(d,uSunDirection));
        daySky+=vec3(0.12,0.10,0.06)*pow(sunward,48.0);
        c=mix(c,daySky,uDaylight);
        gl_FragColor=vec4(c,1.0);} `
  }));
  scene.add(sky); world.sky=sky;

  /* atmosphere shell: halo from orbit, horizon haze from the ground */
  const atm = new THREE.Mesh(new THREE.SphereGeometry(RP*1.07,96,64), new THREE.ShaderMaterial({
    side:THREE.BackSide, transparent:true, depthWrite:false, blending:THREE.AdditiveBlending, uniforms:{uGlow:PALU.uGlow,uDaylight:DAYLIGHT},
    vertexShader:`varying vec3 vN; varying vec3 vW; void main(){ vec4 w=modelMatrix*vec4(position,1.0); vW=w.xyz; vN=normalize(mat3(modelMatrix)*normal); gl_Position=projectionMatrix*viewMatrix*w; }`,
    fragmentShader:`uniform vec3 uGlow; uniform float uDaylight; varying vec3 vN; varying vec3 vW;
      void main(){ vec3 v=normalize(cameraPosition-vW); float f=pow(1.0-abs(dot(normalize(vN),v)),3.0);
        vec3 hazeColour=mix(uGlow*1.3+0.08,vec3(0.35,0.58,0.80),uDaylight);
        gl_FragColor=vec4(hazeColour*f*0.35,1.0);} `
  }));
  scene.add(atm); world.atmosphere=atm;

  /* the globe: land, sea and coast in one mesh */
  {
    const SW=isMobile?260:420, SH=isMobile?170:280;
    const g=new THREE.SphereGeometry(1,SW,SH);
    const p=g.attributes.position, n=p.count;
    const aW=new Float32Array(n), aG=new Float32Array(n), hs=new Float32Array(n), cols=new Float32Array(n*3);
    for(let i=0;i<n;i++){
      const dx=p.getX(i),dy=Math.max(-1,Math.min(1,p.getY(i))),dz=p.getZ(i);
      const th=Math.acos(dy), s=Math.sin(th);
      const ux=s>1e-6?dx/s:0, uz=s>1e-6?dz/s:1;
      const fx=C.x+ux*th*RP, fz=C.z+uz*th*RP;
      const h=heightCore(fx,fz,dx,dy,dz,th,uz);
      hs[i]=h;
      const r=RP+Math.max(h,0);
      p.setXYZ(i,dx*r,dy*r,dz*r);
    }
    g.computeVertexNormals();
    // weld the seam so the toon shading doesn't show a line
    const nr=g.attributes.normal;
    for(let iy=0;iy<=SH;iy++){
      const a=iy*(SW+1), b=a+SW;
      const x=(nr.getX(a)+nr.getX(b))/2,y=(nr.getY(a)+nr.getY(b))/2,z=(nr.getZ(a)+nr.getZ(b))/2;
      nr.setXYZ(a,x,y,z);nr.setXYZ(b,x,y,z);
    }
    const aRS=new Float32Array(n*2);
    for(let i=0;i<n;i++){
      const x=p.getX(i),y=p.getY(i),z=p.getZ(i),h=hs[i];
      const len=Math.hypot(x,y,z), dx=x/len,dy=y/len,dz=z/len;
      if(h<0){ aW[i]=-h; aG[i]=0; continue; }
      const gt=fbm(dx*9,dy*9+2,dz*9,3), warm=smooth(.55,.75,vnoise(dx*5,dy*5+7,dz*5))*0.45;
      const slope=nr.getX(i)*dx+nr.getY(i)*dy+nr.getZ(i)*dz;
      const rk=smooth(0.94,0.70,slope)*smooth(5,14,h);
      const sn=smooth(31,46,h+(vnoise(dx*30,dy*30,dz*30)-.5)*7)*smooth(.40,.86,slope);
      const sd=smooth(1.3,0.65,h);
      cols[i*3]=gt;cols[i*3+1]=warm;cols[i*3+2]=sd; aRS[i*2]=rk; aRS[i*2+1]=sn;
      aW[i]=-1; aG[i]=(1-rk)*(1-sn)*(1-sd);
    }
    g.setAttribute('color',new THREE.BufferAttribute(cols,3));
    g.setAttribute('aW',new THREE.BufferAttribute(aW,1));
    g.setAttribute('aG',new THREE.BufferAttribute(aG,1));
    g.setAttribute('aRS',new THREE.BufferAttribute(aRS,2));
    const ground=new THREE.Mesh(g,toon({key:'ground',vertexColors:true,frag:GROUND_FRAG,uniforms:PALU,
      vHead:'attribute float aW; attribute float aG; attribute vec2 aRS; varying float vWat; varying float vGrass; varying vec2 vRS;\n',
      fHead:'varying float vWat; varying float vGrass; varying vec2 vRS; uniform vec3 uShallow,uDeep,uG1,uG2,uWarm,uWood,uSand,uRock,uSnow,uLandShadow,uKey; uniform float uShadowMix;\n',
      vert:'vWat=aW; vGrass=aG; vRS=aRS;',
      post:`{
        // A cool painted shadow colour for the sandy reference palette, only on the land.
        if(vWat < -0.4 && uShadowMix > 0.0){
          vec3 landNormal=normalize(vWNorm);
          float shade=1.0-smoothstep(0.05,0.55,dot(landNormal,uKey));
          float shadowGrain=tri(vWPos,landNormal,0.11);
          vec3 pigment=uLandShadow*(0.79+0.21*shadowGrain);
          pigment*=0.94+0.06*sin((length(vWPos)-170.0)*0.92+shadowGrain*8.0);
          gl_FragColor.rgb=mix(gl_FragColor.rgb,pigment,shade*uShadowMix);
        }
      }`}));
    ground.receiveShadow=true; ground.castShadow=true; scene.add(ground); world.ground=ground;
  }

  /* everything below is built in flat design space, then wrapped onto the planet */
  const flat = new THREE.Group(); scene.add(flat);

  /* road */
  {
    const N=700, pos=[], idx=[];
    for(let i=0;i<=N;i++){
      const t=i/N, p=curve.getPointAt(t), tan=curve.getTangentAt(t);
      const sx=-tan.z, sz=tan.x, w=lerp(1.75,1.05,smooth(0,.8,t))*(1+0.08*Math.sin(i*0.37));
      for(const s of [-1,1]){const x=p.x+sx*w*s, z=p.z+sz*w*s; pos.push(x,H(x,z)+0.3,z);}
    }
    for(let i=0;i<N;i++){const k=i*2; idx.push(k,k+2,k+1, k+1,k+2,k+3);}
    const g=new THREE.BufferGeometry(); g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3)); g.setIndex(idx);
    const road = new THREE.Mesh(g, toon({key:'road', color:0xece0c2, side:THREE.DoubleSide, polygonOffset:true, polygonOffsetFactor:-2, polygonOffsetUnits:-4, frag:`{
      float sp=step(0.95,h21(floor(vWPos.xz*12.0+vWPos.y*3.1)));
      float rut=vn(vWPos.xz*0.6);
      diffuseColor.rgb*=1.0-0.22*sp-0.08*rut;
    }`}));
    road.receiveShadow=true; flat.add(road);
  }

  /* crag */
  {
    const pts=[];
    for(let i=0;i<=56;i++){const y=lerp(-2,47.7,i/56); pts.push(new THREE.Vector2(cragR(y),y));}
    pts.push(new THREE.Vector2(14,48.1)); pts.push(new THREE.Vector2(0.01,48.2));
    const g=new THREE.LatheGeometry(pts,128);
    const p=g.attributes.position;
    for(let i=0;i<p.count;i++){
      const x=p.getX(i),y=p.getY(i),z=p.getZ(i);
      if(y>47.5) continue;
      const r=Math.hypot(x,z), a=Math.atan2(x,z);
      const n=fbm(x*.07+3,y*.1,z*.07,4)-.5, big=fbm(Math.cos(a)*1.3+7,y*.035,Math.sin(a)*1.3,3)-.5;
      const ledge=0.3*Math.sin(y*0.9+n*6.0);
      const steep=1-0.09*Math.max(0,Math.sin(a))*(1-y/48);
      const k=(r*(1+n*0.16)+big*9*smooth(47,40,y)+ledge)*steep/r;
      p.setXYZ(i,x*k,y,z*k);
    }
    g.computeVertexNormals();
    const nrm=g.attributes.normal, cc=new Float32Array(p.count*3);
    const r1=col(0x8c8470), r2=col(0xbfb49a), mossy=col(0x4f8530), cc0=new THREE.Color();
    for(let i=0;i<p.count;i++){
      const x=p.getX(i),y=p.getY(i),z=p.getZ(i),ny=nrm.getY(i);
      cc0.copy(r1).lerp(r2,fbm(x*.08,y*.12,z*.08,3));
      const green=smooth(.42,.66,ny+(fbm(x*.2,y*.2,z*.2,2)-.5)*.5)*(y<47.5?1:0.25);
      cc0.lerp(mossy,green*0.9);
      cc[i*3]=cc0.r;cc[i*3+1]=cc0.g;cc[i*3+2]=cc0.b;
    }
    g.setAttribute('color',new THREE.BufferAttribute(cc,3));
    const crag=new THREE.Mesh(g, toon({key:'rock', vertexColors:true, frag:ROCK_FRAG}));
    crag.position.set(C.x,0,C.z); crag.castShadow=true; crag.receiveShadow=true; flat.add(crag);
  }

  const stoneMat = toon({key:'stone', color:0xd8ccb0, frag:STONE_FRAG});
  const stoneMatD = toon({key:'stoneD', color:0xd8ccb0, side:THREE.DoubleSide, frag:STONE_FRAG});
  const inkMat = new THREE.MeshBasicMaterial({color:0x0d1640});

  function sectorRing(r0,r1,a0,a1,y,seg){
    const pos=[],idx=[];
    for(let i=0;i<=seg;i++){const a=a0+(a1-a0)*i/seg,s=Math.sin(a),c=Math.cos(a);pos.push(r0*s,y,r0*c,r1*s,y,r1*c);}
    for(let i=0;i<seg;i++){const k=i*2;idx.push(k,k+1,k+2,k+1,k+3,k+2);}
    const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(idx);return g;
  }
  function helix(fn,seg,wallH){
    const pos=[],idx=[],wpos=[];
    for(let i=0;i<=seg;i++){
      const {a,y,r0,r1}=fn(i/seg),s=Math.sin(a),c=Math.cos(a);
      pos.push(r0*s,y,r0*c,r1*s,y,r1*c);
      wpos.push(r1*s,y-1.5,r1*c,r1*s,y+wallH,r1*c);
    }
    for(let i=0;i<seg;i++){const k=i*2;idx.push(k,k+1,k+2,k+1,k+3,k+2);}
    const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(idx);
    const w=new THREE.BufferGeometry();w.setAttribute('position',new THREE.Float32BufferAttribute(wpos,3));w.setIndex(idx.slice());
    return [g,w];
  }
  function arcadeTexture(){
    const cv=document.createElement('canvas');cv.width=256;cv.height=128;const g=cv.getContext('2d');
    g.fillStyle='#ffffff';g.fillRect(0,0,256,128);
    g.strokeStyle='rgba(80,64,40,.35)';g.lineWidth=2;
    for(let y=10;y<128;y+=13){g.beginPath();g.moveTo(0,y);g.lineTo(256,y);g.stroke();}
    g.globalCompositeOperation='destination-out';
    for(let i=0;i<2;i++){const cx=64+i*128,r=40,spring=62;g.beginPath();g.moveTo(cx-r,130);g.lineTo(cx-r,spring);g.arc(cx,spring,r,Math.PI,2*Math.PI);g.lineTo(cx+r,130);g.closePath();g.fill();}
    g.globalCompositeOperation='source-over';
    g.strokeStyle='rgba(40,30,20,.55)';g.lineWidth=4;
    for(let i=0;i<2;i++){const cx=64+i*128,r=42,spring=62;g.beginPath();g.moveTo(cx-r,128);g.lineTo(cx-r,spring);g.arc(cx,spring,r,Math.PI,2*Math.PI);g.lineTo(cx+r,128);g.stroke();}
    const t=new THREE.CanvasTexture(cv);t.wrapS=THREE.RepeatWrapping;t.anisotropy=4;return t;
  }
  const arcTex=arcadeTexture();
  function arcade(Rr,a0,a1,yb,h,spacing){
    const g=new THREE.CylinderGeometry(Rr,Rr,h,Math.ceil((a1-a0)*40),1,true,a0,a1-a0);
    const tex=arcTex.clone();tex.needsUpdate=true;tex.repeat.x=(Rr*(a1-a0)/spacing)/2;
    const m=new THREE.Mesh(g,toon({key:'arc',color:0xdccfb2,map:tex,alphaTest:.5,side:THREE.DoubleSide}));
    m.position.set(C.x,yb+h/2,C.z);m.receiveShadow=true;flat.add(m);
    const band=new THREE.Mesh(new THREE.CylinderGeometry(Rr+.25,Rr+.25,1.1,Math.ceil((a1-a0)*40),1,true,a0,a1-a0),stoneMatD);
    band.position.set(C.x,yb+h+.55,C.z);band.castShadow=true;band.receiveShadow=true;flat.add(band);
    const floor=new THREE.Mesh(sectorRing(cragR(yb+h)-2,Rr+.25,a0,a1,0,64),stoneMatD);
    floor.position.set(C.x,yb+h+1.1,C.z);floor.receiveShadow=true;flat.add(floor);
  }
  const R1=cragR(33.5)+3.4;
  {
    const a0=-2.35,a1=0.55;
    const wall=new THREE.Mesh(new THREE.CylinderGeometry(R1+.1,R1+1.4,7,90,1,true,a0,a1-a0),stoneMatD);
    wall.position.set(C.x,27.5,C.z);wall.castShadow=true;wall.receiveShadow=true;flat.add(wall);
    arcade(R1,a0,a1,31,5.2,4.4);
  }
  {
    const [g,w]=helix(t=>{const y=lerp(12.5,24,t);const r=cragR(y);return {a:lerp(-2.55,-0.35,t),y,r0:r-1.2,r1:r+3.2};},140,1.0);
    const ramp=new THREE.Mesh(g,toon({key:'ramp',color:0xe6d9bb,side:THREE.DoubleSide}));
    ramp.position.set(C.x,0,C.z);ramp.receiveShadow=true;flat.add(ramp);
    const wall=new THREE.Mesh(w,stoneMatD);wall.position.set(C.x,0,C.z);wall.castShadow=true;wall.receiveShadow=true;flat.add(wall);
  }

  /* terrace + tower */
  const tower=new THREE.Group();tower.position.set(C.x,0,C.z);tower.rotation.y=TOWER_ROT;flat.add(tower);
  function box(w,h,d,x,y,z,mat=stoneMat){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;tower.add(m);return m;}
  box(29,6,25,0,45.5,0);
  box(32,3.4,28,0,50.3,0);
  for(const [w,d,x,z] of [[32,.6,0,13.7],[32,.6,0,-13.7],[.6,28,15.7,0],[.6,28,-15.7,0]]) box(w,1.3,d,x,52.6,z);
  {
    const W=16,D=12,Hh=TOWER_H,r=3.8,spring=38,B=TOWER_BASE;
    const s=new THREE.Shape();
    s.moveTo(-W/2,0);s.lineTo(-r,0);s.lineTo(-r,spring);s.absarc(0,spring,r,Math.PI,0,true);s.lineTo(r,0);s.lineTo(W/2,0);s.lineTo(W/2,Hh);s.lineTo(-W/2,Hh);s.lineTo(-W/2,0);
    const g=new THREE.ExtrudeGeometry(s,{depth:D,bevelEnabled:false,curveSegments:28});g.translate(0,0,-D/2);
    const body=new THREE.Mesh(g,stoneMat);body.position.y=B;body.castShadow=true;body.receiveShadow=true;tower.add(body);
    for(const sx of [-1,1]) for(const sz of [-1,1]){
      box(1.3,Hh,.35,sx*(W/2-.65),B+Hh/2,sz*(D/2+.17));
      box(.35,Hh,1.3,sx*(W/2+.17),B+Hh/2,sz*(D/2-.65));
      box(.8,spring,.3,sx*(r+.4),B+spring/2,sz*(D/2+.15));
    }
    box(W+.8,.9,D+.8,0,B+.45,0);
    box(W+.7,1.0,D+.7,0,B+43.2,0);
    box(W+1.4,1.2,D+1.4,0,B+Hh-.2,0);
    box(W+.9,.7,D+.9,0,B+Hh-1.2,0);
    box(W+1.1,.6,D+1.1,0,B+49.8,0);
    const winShape=new THREE.Shape();const ww=.55;
    winShape.moveTo(-ww,0);winShape.lineTo(-ww,2.6);winShape.absarc(0,2.6,ww,Math.PI,0,true);winShape.lineTo(ww,0);winShape.lineTo(-ww,0);
    const wg=new THREE.ShapeGeometry(winShape,10);
    const addWin=(x,y,z,ry)=>{const m=new THREE.Mesh(wg,inkMat);m.position.set(x,y,z);m.rotation.y=ry;tower.add(m);};
    for(let i=0;i<7;i++){const x=-5.4+i*1.8;addWin(x,B+45.2,D/2+.03,0);addWin(-x,B+45.2,-D/2-.03,Math.PI);}
    for(let i=0;i<5;i++){const z=-3.6+i*1.8;addWin(W/2+.03,B+45.2,z,Math.PI/2);addWin(-W/2-.03,B+45.2,-z,-Math.PI/2);}
    const sq=new THREE.PlaneGeometry(.7,.9);
    for(let i=0;i<9;i++){const x=-6+i*1.5;
      const m1=new THREE.Mesh(sq,inkMat);m1.position.set(x,B+Hh-2.6,D/2+.03);tower.add(m1);
      const m2=new THREE.Mesh(sq,inkMat);m2.position.set(x,B+Hh-2.6,-D/2-.03);m2.rotation.y=Math.PI;tower.add(m2);}
    const ring=new THREE.Mesh(new THREE.TorusGeometry(r+.55,.35,6,40,Math.PI),stoneMat);ring.position.set(0,B+spring,D/2+.1);ring.castShadow=true;tower.add(ring);
    const ring2=ring.clone();ring2.position.z=-D/2-.1;tower.add(ring2);
    for(let i=0;i<8;i++){const x=-7+i*2;box(.9,.9,.6,x,B+Hh+.85,D/2+.4);box(.9,.9,.6,x,B+Hh+.85,-D/2-.4);}
  }

  /* wrap the flat-built meshes onto the planet (baked once, so shadows stay correct) */
  flat.updateMatrixWorld(true);
  const baked=[];
  flat.traverse(o=>{ if(o.isMesh) baked.push(o); });
  for(const o of baked){
    const g=o.geometry.clone().applyMatrix4(o.matrixWorld);
    const p=g.attributes.position;
    for(let i=0;i<p.count;i++){ mapFlat(p.getX(i),p.getY(i),p.getZ(i),v3); p.setXYZ(i,v3.x,v3.y,v3.z); }
    g.computeVertexNormals();
    const m=new THREE.Mesh(g,o.material); m.castShadow=o.castShadow; m.receiveShadow=o.receiveShadow;
    scene.add(m);
  }
  scene.remove(flat);

  /* a few small clouds orbiting the globe */
  {
    const cg=new THREE.IcosahedronGeometry(1,3);
    {const p=cg.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i);const k=1+(fbm(x*2.2+9,y*2.2,z*2.2,4)-.5)*.42;p.setXYZ(i,x*k,y*k,z*k);}cg.computeVertexNormals();}
    const cm=new THREE.ShaderMaterial({
      fog:false, uniforms:{uSun:{value:SUN}},
      vertexShader:`varying vec3 vN; varying vec3 vW;
        void main(){ mat4 m=modelMatrix*instanceMatrix; vec4 w=m*vec4(position,1.0); vW=w.xyz; vN=normalize(mat3(m)*normal); gl_Position=projectionMatrix*viewMatrix*w; }`,
      fragmentShader:`uniform vec3 uSun; varying vec3 vN; varying vec3 vW;
        float h21(vec2 p){ p=fract(p*vec2(123.34,456.21)); p+=dot(p,p+45.32); return fract(p.x*p.y); }
        float vn(vec2 p){ vec2 i=floor(p), f=fract(p); f=f*f*(3.-2.*f);
          return mix(mix(h21(i),h21(i+vec2(1.,0.)),f.x), mix(h21(i+vec2(0.,1.)),h21(i+vec2(1.,1.)),f.x), f.y); }
        void main(){
          vec3 n=normalize(vN);
          float t=dot(n,uSun)*0.5+0.5;
          t+=(vn(vW.xy*0.5+vW.z*0.2)-0.5)*0.32+(h21(floor(gl_FragCoord.xy))-0.5)*0.1;
          t+=0.14*dot(n,normalize(vW));
          vec3 c = t>0.62 ? vec3(0.98,0.99,1.0) : t>0.47 ? vec3(0.83,0.88,0.98) : t>0.32 ? vec3(0.60,0.70,0.93) : vec3(0.36,0.48,0.85);
          gl_FragColor=vec4(c,1.0);
        }`
    });
    const puffs=[];   // [x,y,z,size,dirx,diry,dirz]
    const frame=(d)=>{const a=Math.abs(d.y)<0.9?Y:new THREE.Vector3(1,0,0);const t1=new THREE.Vector3().crossVectors(d,a).normalize();return [t1,new THREE.Vector3().crossVectors(d,t1)];};
    const push=(p,sz,d)=>puffs.push([p.x,p.y,p.z,sz,d.x,d.y,d.z]);
    // Six modest clouds around the globe; leave the tower's polar cap clear.
    const cloudRand=mulberry32(197), CR=(a,b)=>a+(b-a)*cloudRand();
    const clusters=[[.38,.2],[-.24,1.25],[.08,2.3],[.5,3.4],[-.32,4.5],[.04,5.55]];
    for(const [u,ph] of clusters){
      const sq=Math.sqrt(1-u*u),d=new THREE.Vector3(sq*Math.cos(ph),u,sq*Math.sin(ph));
      const th=Math.acos(u),fx=C.x+d.x/sq*th*RP,fz=C.z+d.z/sq*th*RP;
      const surface=heightCore(fx,fz,d.x,d.y,d.z,th,d.z/sq);
      const alt=RP+Math.max(0,surface)+CR(22,32),base=CR(5,7),[t1,t2]=frame(d);
      for(let k=0;k<5;k++){
        const p=d.clone().multiplyScalar(alt)
          .addScaledVector(t1,(k-2)*base*.62)
          .addScaledVector(t2,CR(-.32,.32)*base)
          .addScaledVector(d,(k===2?.48:CR(0,.25))*base);
        push(p,base*CR(.65,1),d);
      }
    }
    const im=new THREE.InstancedMesh(cg,cm,puffs.length);
    puffs.forEach((p,i)=>{
      q.setFromUnitVectors(Y,v3.set(p[4],p[5],p[6]));
      const qq=new THREE.Quaternion().setFromAxisAngle(Y,CR(0,6.28));q.multiply(qq);
      m4.compose(new THREE.Vector3(p[0],p[1],p[2]),q,s3.set(p[3],p[3]*.82,p[3]));im.setMatrixAt(i,m4);
    });
    im.frustumCulled=false; im.castShadow=true; scene.add(im);
    world.clouds=im; world.cloudMat=cm;
  }

  /* light: the sun follows the viewer so the side you look at is always lit */
  scene.add(new THREE.AmbientLight(0xc4d2ff,.5));
  const sun=new THREE.DirectionalLight(0xfff2da,.8);
  const tgt=new THREE.Object3D();scene.add(tgt);sun.target=tgt;
  sun.castShadow=true;
  const ms=Math.min(renderer.capabilities.maxTextureSize,isMobile?2048:4096);
  sun.shadow.mapSize.set(ms,ms);
  sun.shadow.bias=-0.0006;sun.shadow.normalBias=0.08;
  scene.add(sun);
  world.sun=sun; world.sunTarget=tgt;
  return world;
}
