// Tower Planet: the shared context. Generated by tests/planet/extract.py from reference/the-tower-planet-clean.html.
// Sueda's noise + helpers (verbatim, reference lines 105-123) are module exports so terrain.js can use them;
// createContext() makes her renderer, scene and camera (lines 102-103, 107-108, 215-226).
// `rand` = mulberry32(11) is kept on ctx for the record: the reference never draws from it, so there is no
// rand order to preserve. The clouds have their own mulberry32(197), inside build.js.
/* ---------------- noise + helpers ---------------- */
function mulberry32(a){return function(){a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;}}
function ihash(x,y,z){let h=Math.imul(x|0,374761393)^Math.imul(y|0,668265263)^Math.imul(z|0,1440662683);h=Math.imul(h^(h>>>13),1274126177);h^=h>>>16;return(h>>>0)/4294967296;}
function vnoise(x,y,z){
  const xi=Math.floor(x),yi=Math.floor(y),zi=Math.floor(z);
  const xf=x-xi,yf=y-yi,zf=z-zi;
  const u=xf*xf*(3-2*xf),v=yf*yf*(3-2*yf),w=zf*zf*(3-2*zf);
  const c000=ihash(xi,yi,zi),c100=ihash(xi+1,yi,zi),c010=ihash(xi,yi+1,zi),c110=ihash(xi+1,yi+1,zi);
  const c001=ihash(xi,yi,zi+1),c101=ihash(xi+1,yi,zi+1),c011=ihash(xi,yi+1,zi+1),c111=ihash(xi+1,yi+1,zi+1);
  const x00=c000+(c100-c000)*u,x10=c010+(c110-c010)*u,x01=c001+(c101-c001)*u,x11=c011+(c111-c011)*u;
  const y0=x00+(x10-x00)*v,y1=x01+(x11-x01)*v;
  return y0+(y1-y0)*w;
}
function fbm(x,y,z,o=4){let a=.5,f=1,s=0,n=0;for(let i=0;i<o;i++){s+=a*vnoise(x*f,y*f,z*f);n+=a;f*=2.03;a*=.5;}return s/n;}
const smooth=(e0,e1,x)=>{const t=Math.min(1,Math.max(0,(x-e0)/(e1-e0)));return t*t*(3-2*t);};
const lerp=(a,b,t)=>a+(b-a)*t;
const col=(h)=>new THREE.Color(h);
export { mulberry32, ihash, vnoise, fbm, smooth, lerp, col };

// Seam: `renderer` may be passed in (the reference always made its own); `canvas` is handed to
// WebGLRenderer when given; `fail` is her fail() from the page.
export function createContext({ canvas = null, renderer = null, fail = (msg) => console.error(msg) } = {}) {
const isMobile = matchMedia('(pointer: coarse)').matches || Math.min(innerWidth, innerHeight) < 560;
const reduceMotion = matchMedia('(prefers-reduced-motion: reduce)').matches;
const rand = mulberry32(11);
const R = (a,b)=>a+(b-a)*rand();

/* ---------------- renderer ---------------- */
  if (!renderer) {
for (const opts of [{antialias:false,powerPreference:'high-performance'},{antialias:false},{antialias:false,precision:'mediump'}]) {
  try { renderer = new THREE.WebGLRenderer(canvas?{...opts,canvas}:opts); break; } catch(e){ console.warn('WebGL init failed', opts, e); }
}
  }
if(!renderer){ fail('Your browser could not start WebGL. Turn on hardware acceleration in the browser settings, then reload.'); return; }
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;
  if (!renderer.domElement.isConnected)
document.body.prepend(renderer.domElement);

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(40, innerWidth/innerHeight, 0.8, 9000);
  return { THREE, renderer, scene, camera, isMobile, reduceMotion, rand, R, fail };
}
