// Tower Planet materials. Generated by tests/planet/extract.py from reference/the-tower-planet-clean.html.
// Her toon material, GLSL chunks, palette uniforms (lines 227-332) and colours (991-1005), verbatim.
const GLSL_COMMON = `
varying vec3 vWPos; varying vec3 vWNorm;
float h21(vec2 p){ p=fract(p*vec2(123.34,456.21)); p+=dot(p,p+45.32); return fract(p.x*p.y); }
float vn(vec2 p){ vec2 i=floor(p), f=fract(p); f=f*f*(3.-2.*f);
  return mix(mix(h21(i),h21(i+vec2(1.,0.)),f.x), mix(h21(i+vec2(0.,1.)),h21(i+vec2(1.,1.)),f.x), f.y); }
float tri(vec3 p, vec3 n, float f){ vec3 w=pow(abs(n),vec3(4.0)); w/=(w.x+w.y+w.z+1e-4);
  return w.x*vn(p.yz*f)+w.y*vn(p.xz*f)+w.z*vn(p.xy*f); }
`;

const STONE_FRAG = `{
  vec3 n=normalize(vWNorm);
  vec2 t=normalize(vec2(-n.z,n.x)+1e-4);
  float u=dot(vWPos.xz,t);
  float rowH=1.15;
  float row=floor(vWPos.y/rowH), fy=fract(vWPos.y/rowH);
  float bu=u/2.6+0.5*mod(row,2.0), fx=fract(bu), cl=floor(bu);
  float mortar=max(1.0-step(0.08,fy), 1.0-step(0.035,fx));
  if(abs(n.y)>0.8) mortar=0.0;
  float tint=h21(vec2(row,cl))*0.16-0.08;
  float grain=vn(vWPos.xy*2.7+vWPos.zy*2.3)*0.12;
  diffuseColor.rgb*=(1.0+tint*0.7-grain*0.7)*mix(1.0,0.82,mortar);
}`;
const ROCK_FRAG = `{
  float s=vn(vec2(atan(vWPos.x,vWPos.z)*38.0, vWPos.y*0.35));
  float c=vn(vWPos.xz*0.5+vWPos.y*0.3);
  diffuseColor.rgb*=0.86+0.22*s-0.08*c;
}`;
const GROUND_FRAG = `{
  vec3 n=normalize(vWNorm);
  if(vWat>-0.4){
    diffuseColor.rgb=mix(uShallow,uDeep,smoothstep(0.2,5.5,max(vWat,0.0)));
  } else {
    vec3 b=mix(uG1,uG2,clamp((vColor.r-0.25)*2.0,0.0,1.0));
    b=mix(b,uWarm,vColor.g);
    b=mix(b,uRock,vRS.x); b=mix(b,uSnow,vRS.y); b=mix(b,uSand,vColor.b);
    diffuseColor.rgb=b;
  }
  if(vWat>-0.4){
    float depth=max(vWat,0.0);
    float r=tri(vWPos+vec3(uTime*0.5,0.0,uTime*0.2),n,0.3);
    float foam=(1.0-smoothstep(0.0,0.9,depth))*step(0.42,tri(vWPos,n,1.2));
    float crest=smoothstep(0.8,0.9,r)*0.45;
    diffuseColor.rgb=mix(diffuseColor.rgb,vec3(0.93,0.96,1.0),max(foam*0.9,crest));
  } else {
    float d=length(vWPos-cameraPosition);
    float strokes=smoothstep(0.6,0.8,tri(vWPos,n,2.6));
    float patches=tri(vWPos,n,0.09);
    float fade=1.0-smoothstep(25.0,300.0,d);
    diffuseColor.rgb*=1.0-0.2*strokes*fade-0.12*(patches-0.5);
    float big=tri(vWPos+3.1,n,0.075)+0.5*tri(vWPos+9.7,n,0.19)-0.25;
    float rag=(tri(vWPos,n,0.7)-0.5)*0.12+(tri(vWPos,n,2.1)-0.5)*0.05;
    float dark=smoothstep(0.75,0.78,big+rag);
    float hl=abs(tri(vWPos*vec3(1.0,1.0,2.6)+7.0,n,0.02)-0.5);
    float hedge=1.0-smoothstep(0.010,0.018,hl+rag*0.08);
    float dm=max(dark,hedge*0.9)*vGrass;
    float speck=step(0.82,h21(floor(vWPos.xz*2.5+vWPos.y*1.7)));
    vec3 wood=mix(uWood,uWood*1.7+0.03,speck*0.8);
    diffuseColor.rgb=mix(diffuseColor.rgb,wood,dm*0.76);
    // World-anchored washes, sediment bands and scree remain readable at orbit distance.
    float height=length(vWPos)-170.0;
    float wash=tri(vWPos+23.0,n,0.065);
    float relief=1.0-clamp(dot(n,normalize(vWPos)),0.0,1.0);
    float strata=0.5+0.5*sin(height*0.92+tri(vWPos+7.0,n,0.055)*8.0);
    float erosion=pow(1.0-abs(2.0*tri(vWPos+13.0,n,0.14)-1.0),5.0);
    float pebbles=tri(vWPos+41.0,n,0.42)-0.5;
    float nearGrain=tri(vWPos,n,2.1)-0.5;
    diffuseColor.rgb*=0.86+0.23*wash+0.10*(strata-0.5)*smoothstep(0.025,0.22,relief);
    diffuseColor.rgb*=1.0-0.17*erosion+0.12*pebbles+0.09*nearGrain*fade;
    diffuseColor.rgb=mix(diffuseColor.rgb,uSand*1.035,(1.0-strata)*0.065*(1.0-vRS.y));
  }
}`;
const COLOUR_KEYS=[['bg','Space'],['glow','Glow'],['shallow','Shallow sea'],['deep','Deep sea'],['g2','Light land'],['g1','Land'],['wood','Land patches'],['sand','Sand'],['rock','Rock'],['shadow','Land shadows']];
const DEFAULT_COLOURS={bg:'#05060d',glow:'#1e3cc4',shallow:'#65c7c4',deep:'#4b8ba2',g2:'#f1d8a2',g1:'#d3bb89',wood:'#b5a474',sand:'#f4dfab',rock:'#979cb7',shadow:'#8187af'};
export { GLSL_COMMON, STONE_FRAG, ROCK_FRAG, GROUND_FRAG, COLOUR_KEYS, DEFAULT_COLOURS };

// her uniforms + the toon factory, made per planet (in the reference they sat in the closure)
export function createMaterials(ctx) {
const uTime = {value:0};
const SUN = new THREE.Vector3(-0.5,0.6,0.6).normalize();
const BG = {value:new THREE.Color(0x05060d)};
const DAYLIGHT = {value:0};
const PALU = {uShallow:{value:new THREE.Color()},uDeep:{value:new THREE.Color()},uG1:{value:new THREE.Color()},uG2:{value:new THREE.Color()},
  uWarm:{value:new THREE.Color()},uWood:{value:new THREE.Color()},uSand:{value:new THREE.Color()},
  uLandShadow:{value:new THREE.Color(0x8187af)},uShadowMix:{value:0},uKey:{value:SUN},
  uRock:{value:new THREE.Color(0x8f8876)},uSnow:{value:new THREE.Color(0xf3f1ea)},uGlow:{value:new THREE.Color()}};

const gradTex = new THREE.DataTexture(new Uint8Array([60,60,60,255, 128,128,128,255, 196,196,196,255, 255,255,255,255]),4,1,THREE.RGBAFormat);
gradTex.minFilter=gradTex.magFilter=THREE.NearestFilter; gradTex.generateMipmaps=false; gradTex.needsUpdate=true;
function toon(opts){
  const {color=0xffffff, key, frag='', vert='', vHead='', fHead='', post='', uniforms=null, ...rest} = opts;
  const m = new THREE.MeshToonMaterial({color, gradientMap:gradTex, ...rest});
  m.onBeforeCompile = (sh)=>{
    sh.uniforms.uTime = uTime; if(uniforms) Object.assign(sh.uniforms,uniforms);
    sh.vertexShader = 'uniform float uTime;\n'+vHead+GLSL_COMMON+sh.vertexShader
      .replace('#include <begin_vertex>','#include <begin_vertex>\n'+vert)
      .replace('#include <project_vertex>',`#include <project_vertex>
        #ifdef USE_INSTANCING
          vWPos=(modelMatrix*instanceMatrix*vec4(transformed,1.0)).xyz;
          vWNorm=normalize(mat3(modelMatrix)*mat3(instanceMatrix)*objectNormal);
        #else
          vWPos=(modelMatrix*vec4(transformed,1.0)).xyz;
          vWNorm=normalize(mat3(modelMatrix)*objectNormal);
        #endif`);
    sh.fragmentShader = 'uniform float uTime;\n'+fHead+GLSL_COMMON+sh.fragmentShader
      .replace('#include <color_fragment>','#include <color_fragment>\n'+frag)
      .replace('#include <tonemapping_fragment>',post+'\n#include <tonemapping_fragment>');
  };
  m.customProgramCacheKey = ()=>'toon-'+key;
  return m;
}
  return { uTime, SUN, BG, DAYLIGHT, PALU, gradTex, toon };
}

// her colour model (lines 993-1005). The DOM half (pickers, --bg / --hint) moved to ui.js, behind `emit`.
export function createColours(ctx, emit = () => {}) {
  const { BG, PALU } = ctx;
  const current = {};
const UNI={bg:BG,glow:PALU.uGlow,shallow:PALU.uShallow,deep:PALU.uDeep,g2:PALU.uG2,g1:PALU.uG1,wood:PALU.uWood,sand:PALU.uSand,rock:PALU.uRock,shadow:PALU.uLandShadow};
const warmTint=new THREE.Color('#ebbe84');
PALU.uSnow.value.set('#ede4c8');PALU.uShadowMix.value=.86;
function setColour(k,hex){
  UNI[k].value.set(hex);current[k]=hex;
  if(k==='g2')PALU.uWarm.value.copy(PALU.uG2.value).lerp(warmTint,.3);
  emit(k,hex);
}
  for(const [k] of COLOUR_KEYS) setColour(k,DEFAULT_COLOURS[k]);
  return { UNI, warmTint, setColour, getColours: () => ({ ...current }) };
}
