// Tower Planet post. Generated by tests/planet/extract.py from reference/the-tower-planet-clean.html.
// Her Red Arch gouache pass (Kuwahara, edges, pencil line), the lens + grain + gouache finish, the render
// targets and renderFinish, verbatim (reference lines 687-911). renderFinish reads the world from ctx.world.
export function createPost(ctx){
  const { renderer, scene, camera } = ctx;
/* ---------------- Red Arch gouache pass ---------------- */
  const GLSL_NOISE = `
    float hash(vec2 p){ p = fract(p*vec2(123.34,456.21)); p += dot(p, p+45.32); return fract(p.x*p.y); }
    float vnoise(vec2 p){ vec2 i=floor(p), f=fract(p); vec2 u=f*f*(3.0-2.0*f);
      return mix(mix(hash(i),hash(i+vec2(1.0,0.0)),u.x), mix(hash(i+vec2(0.0,1.0)),hash(i+vec2(1.0,1.0)),u.x), u.y); }
    float fbm(vec2 p){ float a=0.5, s=0.0; for(int i=0;i<4;i++){ s+=a*vnoise(p); p*=2.03; a*=0.5; } return s; }
  `;
  const FS_VERT = `varying vec2 vUv; void main(){ vUv = uv; gl_Position = vec4(position.xy, 0.0, 1.0); }`;

  // 1. gouache: warped generalised Kuwahara, flattens the CG into brush-shaped patches
  const kuwaharaMat = new THREE.ShaderMaterial({
    uniforms: { tDiffuse: { value: null }, uRes: { value: new THREE.Vector2() }, uRadius: { value: 4 }, uWarp: { value: 1 }, uWarmth: { value: 0.6 } },
    vertexShader: FS_VERT,
    fragmentShader: GLSL_NOISE + `
      uniform sampler2D tDiffuse; uniform vec2 uRes; uniform float uRadius, uWarp, uWarmth; varying vec2 vUv;
      void main(){
        vec2 px = 1.0/uRes;
        vec2 warp = (vec2(fbm(vUv*uRes/22.0), fbm(vUv*uRes/22.0 + 9.7)) - 0.5) * 3.0 * uWarp * px;
        vec2 uv = vUv + warp;
        vec3 m0=vec3(0.0), m1=vec3(0.0), m2=vec3(0.0), m3=vec3(0.0);
        vec3 s0=vec3(0.0), s1=vec3(0.0), s2=vec3(0.0), s3=vec3(0.0);
        float n0=0.0, n1=0.0, n2=0.0, n3=0.0;
        for (int j=-6; j<=6; j++) for (int i=-6; i<=6; i++) {
          if (abs(float(i)) > uRadius || abs(float(j)) > uRadius) continue;
          vec3 c = texture2D(tDiffuse, uv + vec2(float(i), float(j))*px).rgb, c2 = c*c;
          if (i<=0 && j<=0) { m0+=c; s0+=c2; n0+=1.0; }
          if (i>=0 && j<=0) { m1+=c; s1+=c2; n1+=1.0; }
          if (i<=0 && j>=0) { m2+=c; s2+=c2; n2+=1.0; }
          if (i>=0 && j>=0) { m3+=c; s3+=c2; n3+=1.0; }
        }
        m0/=n0; m1/=n1; m2/=n2; m3/=n3;
        vec3 v0=abs(s0/n0-m0*m0), v1=abs(s1/n1-m1*m1), v2=abs(s2/n2-m2*m2), v3=abs(s3/n3-m3*m3);
        float e0=v0.r+v0.g+v0.b, e1=v1.r+v1.g+v1.b, e2=v2.r+v2.g+v2.b, e3=v3.r+v3.g+v3.b;
        // soft blend weighted by inverse variance — less blocky than picking one quadrant
        float w0=1.0/(1.0+pow(e0*900.0,2.0)), w1=1.0/(1.0+pow(e1*900.0,2.0)), w2=1.0/(1.0+pow(e2*900.0,2.0)), w3=1.0/(1.0+pow(e3*900.0,2.0));
        vec3 c = (m0*w0+m1*w1+m2*w2+m3*w3)/(w0+w1+w2+w3);
        // gentle warm grade, lifted blacks like gouache on paper
        c = pow(c, vec3(0.96));
        c = mix(c, c*vec3(1.04,1.0,0.94), uWarmth);
        c = max(c, vec3(0.06,0.05,0.06));
        gl_FragColor = vec4(c, 1.0);
      }`
  });

  // 2. edges from depth + normals of the smooth proxy world
  const edgeMat = new THREE.ShaderMaterial({
    uniforms: { tNormal: { value: null }, tDepth: { value: null }, uRes: { value: new THREE.Vector2() }, cameraNear: { value: camera.near }, cameraFar: { value: camera.far } },
    vertexShader: FS_VERT,
    fragmentShader: `
      uniform sampler2D tNormal, tDepth; uniform vec2 uRes; uniform float cameraNear, cameraFar; varying vec2 vUv;
      float lin(float d){ float z = d*2.0-1.0; return (2.0*cameraNear*cameraFar)/(cameraFar+cameraNear-z*(cameraFar-cameraNear)); }
      void main(){
        vec2 px = 1.0/uRes;
        float d0 = lin(texture2D(tDepth, vUv).x); vec3 n0 = texture2D(tNormal, vUv).xyz*2.0-1.0;
        float e = 0.0;
        for (int k=0; k<8; k++) {
          vec2 o = k==0?vec2(1,0):k==1?vec2(-1,0):k==2?vec2(0,1):k==3?vec2(0,-1):k==4?vec2(1,1):k==5?vec2(-1,1):k==6?vec2(1,-1):vec2(-1,-1);
          float d = lin(texture2D(tDepth, vUv+o*px).x); vec3 n = texture2D(tNormal, vUv+o*px).xyz*2.0-1.0;
          e = max(e, smoothstep(0.035, 0.07, (d-d0)/d0));                  // only the nearer side draws
          e = max(e, smoothstep(0.45, 0.75, 1.0-dot(n,n0)) * step(d0, d*1.002) * 0.85);
        }
        gl_FragColor = vec4(e, 0.0, 0.0, 1.0);
      }`
  });


  const paintLineMat = new THREE.ShaderMaterial({
    uniforms: {tEdge:{value:null},uRes:{value:new THREE.Vector2()},uLineMax:{value:3.4},uScale:{value:1}},
    vertexShader: FS_VERT,
    fragmentShader: GLSL_NOISE + `
      uniform sampler2D tEdge; uniform vec2 uRes; uniform float uLineMax,uScale; varying vec2 vUv;
      void main(){
        vec2 px = 1.0/uRes;
        vec2 q = vUv*uRes/uScale;
        // keyline: unequal weight (mostly fine, sometimes heavy), with lost edges
        float wN = vnoise(q/70.0 + 3.1);
        float w = mix(0.7, uLineMax, pow(wN, 2.2)) * uScale;
        float line = 0.0;
        for (int j=-5; j<=5; j++) for (int i=-5; i<=5; i++) {
          float d = length(vec2(float(i), float(j)));
          if (d > w + 0.5) continue;
          float e = texture2D(tEdge, vUv + vec2(float(i), float(j))*px).r;
          line = max(line, e * (1.0 - smoothstep(w - 0.5, w + 0.5, d)));
        }
        line *= smoothstep(0.18, 0.42, vnoise(q/45.0 + 17.0));   // lost edges
        line *= 0.75 + 0.25*vnoise(q/9.0);                        // pressure

        gl_FragColor=vec4(0.0,0.0,0.0,line);
      }`
  });
  [kuwaharaMat,edgeMat,paintLineMat].forEach(m=>{m.depthTest=false;m.depthWrite=false;});

/* ---------------- lens, grain and gouache ---------------- */
const post = new THREE.ShaderMaterial({
  uniforms:{tColor:{value:null},tDepth:{value:null},tPaint:{value:null},tPaintLine:{value:null},
    uBlend:{value:0},uPaperTooth:{value:.1},uPooling:{value:.06},uPencil:{value:.55},uPaintWarp:{value:1},uPaintSat:{value:1.06},
    uRes:{value:new THREE.Vector2()},uOut:{value:new THREE.Vector2()},
    uNear:{value:camera.near},uFar:{value:camera.far},uLine:{value:1.5},uPR:{value:1},
    uFish:{value:.38},uGrain:{value:.75},uSize:{value:1.4}},
  vertexShader:`varying vec2 vUv; void main(){ vUv=uv; gl_Position=vec4(position.xy,0.0,1.0); }`,
  fragmentShader:GLSL_NOISE+`
    #include <packing>
    uniform sampler2D tColor; uniform sampler2D tDepth,tPaint,tPaintLine;
    uniform float uBlend,uPaperTooth,uPooling,uPencil,uPaintWarp,uPaintSat;
    uniform vec2 uRes, uOut; uniform float uNear,uFar,uLine,uPR,uGrain,uSize,uFish;
    varying vec2 vUv;
    const vec3 INK=vec3(0.04,0.07,0.26);
    float LD(vec2 uv){ float d=texture2D(tDepth,uv).x; return log(-perspectiveDepthToViewZ(d,uNear,uFar)); }
    float lum(vec3 c){ return dot(c,vec3(0.299,0.587,0.114)); }
    vec2 fish(vec2 uv){
      float a=uOut.x/uOut.y; vec2 p=(uv-0.5)*vec2(a,1.0);
      float r2=dot(p,p); p*=1.0/(1.0+uFish*r2);
      return p/vec2(a,1.0)+0.5;
    }
    float Lc(vec2 uv){ return lum(texture2D(tColor,uv).rgb); }

    vec3 grade(vec3 c){
      float l=lum(c);
      c=mix(vec3(l),c,1.22);
      return clamp(c,0.0,1.0);
    }
    vec3 gradeAt(vec2 uv){
      vec3 c=texture2D(tColor,uv).rgb;
      if(LD(uv)>log(4000.0)) return c;
      return grade(c);
    }
    float edgeAt(vec2 uv, out float dC){
      vec2 px=uLine/uRes;
      dC=LD(uv);
      float dL=LD(uv-vec2(px.x,0.)), dR=LD(uv+vec2(px.x,0.)), dD=LD(uv-vec2(0.,px.y)), dU=LD(uv+vec2(0.,px.y));
      float lap=abs(dL+dR-2.0*dC)+abs(dU+dD-2.0*dC);
      float de=smoothstep(0.035,0.09,lap);
      float l00=Lc(uv+px*vec2(-1,-1)), l10=Lc(uv+px*vec2(0,-1)), l20=Lc(uv+px*vec2(1,-1));
      float l01=Lc(uv+px*vec2(-1,0)), l21=Lc(uv+px*vec2(1,0));
      float l02=Lc(uv+px*vec2(-1,1)), l12=Lc(uv+px*vec2(0,1)), l22=Lc(uv+px*vec2(1,1));
      float gx=(l20+2.0*l21+l22)-(l00+2.0*l01+l02), gy=(l02+2.0*l12+l22)-(l00+2.0*l10+l20);
      float ce=smoothstep(0.32,0.7,length(vec2(gx,gy)));
      float nearF=1.0-smoothstep(250.0,900.0,exp(dC));
      return max(de, ce*0.45*nearF);
    }
    vec3 grainAt(vec2 fuv,vec2 fc){
      float dC;
        vec3 c=gradeAt(fuv);
        float e=edgeAt(fuv,dC);
        vec2 gp=floor(fc/max(uSize*0.75,1.0));
        vec3 n=vec3(hash(gp),hash(gp+17.31),hash(gp+41.77));
        float clump=vnoise(fc*0.35)-0.5;                          // clustered, not pure white noise
        n=clamp(n+clump*0.35*uGrain,0.0,1.0);
        float N=6.0;
        vec3 q=floor(c*N+mix(vec3(0.5),n,uGrain))/N;
        if(dC>log(4000.0)) q=c*(1.0+(n.x-0.5)*0.5*uGrain)+(n.y-0.5)*0.03*uGrain;   // leave the chosen background its own colour, just grained
        q=mix(q,INK,e*0.85);
        return q;
    }

    void main(){
      vec2 fc=gl_FragCoord.xy/uPR;
      vec2 fuv=fish(vUv);
      if(uBlend<0.001){gl_FragColor=vec4(clamp(grainAt(fuv,fc),0.0,1.0),1.0);return;}
      // Red Arch gouache, with the lens applied to both paint and pencil.
      vec2 wob=(vec2(vnoise(fc/16.0),vnoise(fc/16.0+7.0))-0.5)*1.6*uPaintWarp*uPR/uOut;
      vec2 uv=fish(vUv+wob);
      vec3 c=texture2D(tPaint,uv).rgb;
      vec3 skyDetail=texture2D(tColor,fuv).rgb;
      float isSky=smoothstep(3500.0,4500.0,exp(LD(fuv)));
      float starHighlight=smoothstep(0.06,0.24,max(skyDetail.r,max(skyDetail.g,skyDetail.b))-dot(c,vec3(.3,.59,.11)));
      c=mix(c,max(c,skyDetail),isSky*starHighlight);
      float l=smoothstep(0.3,0.65,texture2D(tPaintLine,uv).a);
      c=mix(c,c*vec3(0.32,0.28,0.36),l*uPencil);
      c=mix(vec3(dot(c,vec3(0.3,0.59,0.11))),c,uPaintSat);
      float fib=fbm(fc/2.2);
      c*=1.0-uPaperTooth*(1.0-fib);
      c*=1.0-uPooling*smoothstep(0.55,0.75,fbm(fc/9.0));
      if(uBlend<0.999)c=mix(grainAt(fuv,fc),c,uBlend);
      gl_FragColor=vec4(clamp(c,0.0,1.0),1.0);
    }`
});


const postScene=new THREE.Scene(), postCam=new THREE.OrthographicCamera(-1,1,1,-1,0,1);
const postQuad=new THREE.Mesh(new THREE.PlaneGeometry(2,2),post);
postQuad.frustumCulled=false;postScene.add(postQuad);
post.depthTest=false;post.depthWrite=false;
function paintPass(material,target){postQuad.material=material;renderer.setRenderTarget(target);renderer.render(postScene,postCam);}
const paintNormalMat=new THREE.MeshNormalMaterial({side:THREE.DoubleSide});
let rtPaint,rtPaintNormal,rtPaintEdge,rtPaintLine;
let rt;
function makeRT(w,h){
  if(rt){rt.depthTexture.dispose();rt.dispose();}
  rt=new THREE.WebGLRenderTarget(w,h,{minFilter:THREE.LinearFilter,magFilter:THREE.LinearFilter,format:THREE.RGBAFormat,depthBuffer:true,stencilBuffer:false});
  rt.depthTexture=new THREE.DepthTexture(w,h);rt.depthTexture.type=THREE.UnsignedIntType;
  post.uniforms.tColor.value=rt.texture;post.uniforms.tDepth.value=rt.depthTexture;post.uniforms.uRes.value.set(w,h);
  for(const target of [rtPaint,rtPaintNormal,rtPaintEdge,rtPaintLine]){
    if(target){if(target.depthTexture)target.depthTexture.dispose();target.dispose();}
  }
  rtPaint=rtPaintNormal=rtPaintEdge=rtPaintLine=null;
  const opts={minFilter:THREE.LinearFilter,magFilter:THREE.LinearFilter,depthBuffer:false,stencilBuffer:false};
  rtPaint=new THREE.WebGLRenderTarget(w,h,opts);
  rtPaintNormal=new THREE.WebGLRenderTarget(w,h,{minFilter:THREE.NearestFilter,magFilter:THREE.NearestFilter});
  rtPaintEdge=new THREE.WebGLRenderTarget(w,h,opts);rtPaintLine=new THREE.WebGLRenderTarget(w,h,opts);
  for(const mat of [kuwaharaMat,edgeMat,paintLineMat])mat.uniforms.uRes.value.set(w,h);
  paintLineMat.uniforms.uScale.value=Math.max(.7,Math.max(w,h)/1000);
  kuwaharaMat.uniforms.tDiffuse.value=rt.texture;
  edgeMat.uniforms.tNormal.value=rtPaintNormal.texture;
  // Use the colour pass depth so cut-out arcade openings remain open in the pencil pass.
  edgeMat.uniforms.tDepth.value=rt.depthTexture;
  paintLineMat.uniforms.tEdge.value=rtPaintEdge.texture;
  post.uniforms.tPaint.value=rtPaint.texture;post.uniforms.tPaintLine.value=rtPaintLine.texture;
  kuwaharaMat.uniforms.uRadius.value=Math.max(1,Math.min(6,Math.round(4*Math.max(w,h)/1000)));
}
function renderFinish(){
  const world=ctx.world;
  if(post.uniforms.uBlend.value>=.001){
    // The atmosphere and sky contribute colour, never hard pencil contours.
    const skyVisible=world.sky.visible, atmosphereVisible=world.atmosphere.visible;
    const shadows=renderer.shadowMap.enabled;
    const clear=renderer.getClearColor(new THREE.Color()), alpha=renderer.getClearAlpha();
    world.sky.visible=world.atmosphere.visible=false;
    renderer.shadowMap.enabled=false;scene.overrideMaterial=paintNormalMat;
    renderer.setClearColor(0x8080ff,1);renderer.setRenderTarget(rtPaintNormal);renderer.render(scene,camera);
    scene.overrideMaterial=null;renderer.shadowMap.enabled=shadows;
    renderer.setClearColor(clear,alpha);world.sky.visible=skyVisible;world.atmosphere.visible=atmosphereVisible;
    paintPass(kuwaharaMat,rtPaint);paintPass(edgeMat,rtPaintEdge);paintPass(paintLineMat,rtPaintLine);
  }
  paintPass(post,null);
}
  return {
    post, kuwaharaMat, edgeMat, paintLineMat, paintNormalMat, postScene, postCam, postQuad,
    paintPass, makeRT, renderFinish,
    get rt(){ return rt; },
    get targets(){ return { rt, rtPaint, rtPaintNormal, rtPaintEdge, rtPaintLine }; }
  };
}
