// Tower Planet terrain. Generated by tests/planet/extract.py from reference/the-tower-planet-clean.html.
// Above the line: Sueda's flat design space, the road and the height field, verbatim (reference lines 125-213).
// Below the line: the surface API the game uses to live on the sphere (new code, docs/planet.md).
// Needs the global THREE (the road curve is a THREE.CatmullRomCurve3).
import { vnoise, fbm, smooth, lerp } from './context.js';

/* ---------------- the world ---------------- */
const C = {x:8, z:-150};          // crag centre in the "flat" design space; it sits on the planet's pole
const RP = 170;                   // planet radius
const TOWER_BASE = 52, TOWER_H = 58, TOWER_ROT = -0.28;

/* flat design space -> planet: distance from C becomes an arc, height becomes altitude */
function mapFlat(fx,y,fz,out){
  const rx=fx-C.x, rz=fz-C.z, d=Math.hypot(rx,rz), r=RP+y;
  if(d<1e-9) return out.set(0,r,0);
  const th=d/RP, s=Math.sin(th);
  return out.set(s*rx/d*r, Math.cos(th)*r, s*rz/d*r);
}

/* the road */
const pathPts=[[2.6,44],[2.2,24],[1.6,10],[0.9,-2],[-1.1,-13],[-3.2,-23],[-2.4,-33],[2.8,-42],[9,-51],[7.5,-60],[-3.5,-67],[-17,-74],[-24.5,-82],[-16,-89.5],[-1,-94],[13,-98],[21,-104]];
const curve = new THREE.CatmullRomCurve3(pathPts.map(p=>new THREE.Vector3(p[0],0,p[1])),false,'centripetal');
const PS = curve.getSpacedPoints(170).map(v=>[v.x,v.z]);
const PB = {x0:-30,x1:28,z0:-110,z1:50};
function pathDist(x,z){
  const bx=Math.max(PB.x0-x,0,x-PB.x1), bz=Math.max(PB.z0-z,0,z-PB.z1);
  if(bx>25||bz>25) return Math.hypot(bx,bz);
  let m=1e9;
  for(let i=0;i<PS.length-1;i++){
    const ax=PS[i][0],az=PS[i][1],dx=PS[i+1][0]-ax,dz=PS[i+1][1]-az;
    let t=((x-ax)*dx+(z-az)*dz)/(dx*dx+dz*dz); t=t<0?0:t>1?1:t;
    const ex=ax+dx*t-x,ez=az+dz*t-z,d=ex*ex+ez*ez; if(d<m)m=d;
  }
  return Math.sqrt(m);
}

/* home meadow (flat design space) */
function Hland(x,z){
  const nearTame = lerp(0.35,1,smooth(0,-70,z));
  let h=(fbm(x*.011,1.7,z*.011,4)-.5)*8*nearTame;
  h+=(fbm(x*.045,5.3,z*.045,3)-.5)*1.5;
  h+=4.5*smooth(15,-95,z);
  const dx=x-C.x,dz=z-C.z; h+=10*Math.exp(-(dx*dx+dz*dz)/(64*64));
  const pd=pathDist(x,z);
  h-=0.35*(1-smooth(.5,5,pd));
  h+=Math.min(pd,22)*0.07*(1-smooth(-8,-45,z));
  // Broken mountain chains flank the meadow; the road and tower keep their clear approaches.
  const west=Math.exp(-Math.pow((x+74+Math.sin(z*.022)*14)/27,2)-Math.pow((z+48)/86,2));
  const east=Math.exp(-Math.pow((x-82-Math.sin(z*.019)*13)/30,2)-Math.pow((z+78)/69,2));
  const ridge=1-Math.abs(2*vnoise(x*.032+4,3.1,z*.032)-1);
  const cut=1-Math.abs(2*vnoise(x*.086,9.2,z*.086)-1);
  const clearance=smooth(9,26,pd)*smooth(48,74,Math.hypot(dx,dz));
  h+=Math.max(west*39,east*46)*(.25+.61*Math.pow(ridge,2.8)+.14*Math.pow(cut,3))*clearance;
  h+=(vnoise(x*.13,7.1,z*.13)-.5)*1.6*clearance;
  return h+2.2;
}
/* the rest of the globe, on the unit sphere */
function Hfar(dx,dy,dz,mount){
  let h=3.2+(fbm(dx*3+11,dy*3,dz*3,4)-.5)*11;
  const belt=smooth(.40,.63,fbm(dx*1.8+3,dy*1.8+1,dz*1.8,3))*mount;
  const warp=(vnoise(dx*3+9,dy*3-2,dz*3+6)-.5)*.6;
  const spine=1-Math.abs(2*vnoise(dx*6+2+warp,dy*6-warp,dz*6+warp)-1);
  const ridge=1-Math.abs(2*vnoise(dx*17+3,dy*17+8,dz*17)-1);
  const scree=1-Math.abs(2*vnoise(dx*41,dy*41+5,dz*41)-1);
  h+=belt*(7+Math.pow(spine,3.2)*43+Math.pow(ridge,3)*13+Math.pow(scree,4)*3);
  return h;
}
function landMask(dx,dy,dz,th,uz){
  const rh=0.66+0.62*Math.max(0,uz)+0.12*Math.max(0,-uz)+(fbm(dx*2.6,dy*2.6+4,dz*2.6,3)-.5)*0.5;
  const home=smooth(rh+.05,rh-.05,th);
  const c=fbm(dx*1.9+7.3,dy*1.9,dz*1.9+2.1,4);
  const cont=smooth(.56,.58,c)*smooth(0.95,1.35,th);
  return Math.max(home,cont);
}
function heightCore(fx,fz,dx,dy,dz,th,uz){
  const b=smooth(0.95,1.5,th);
  const hl=b<1?Hland(fx,fz):0;
  const hf=b>0?Hfar(dx,dy,dz,smooth(1.25,1.75,th)):0;
  const h=lerp(hl,hf,b);
  const land=landMask(dx,dy,dz,th,uz);
  return lerp(-7,Math.max(h,0.6),land);
}
function H(fx,fz){
  const rx=fx-C.x, rz=fz-C.z, d=Math.hypot(rx,rz), th=d/RP, s=Math.sin(th);
  const ux=d>1e-6?rx/d:0, uz=d>1e-6?rz/d:1;
  return heightCore(fx,fz,s*ux,Math.cos(th),s*uz,th,uz);
}

/* crag profile: [radius, y] */
const prof=[[48,-2],[39,6],[33.5,11],[29.5,15.5],[27,19.5],[25.4,23.5],[24.3,27.5],[23.4,31.5],[22.6,35.5],[21.9,39.5],[21.2,43.5],[20.6,46.4],[20,47.7]];
function cragR(y){
  if(y<=prof[0][1])return prof[0][0];
  for(let i=0;i<prof.length-1;i++){const a=prof[i],b=prof[i+1];if(y<=b[1])return lerp(a[0],b[0],(y-a[1])/(b[1]-a[1]));}
  return prof[prof.length-1][0];
}

export { C, RP, TOWER_BASE, TOWER_H, TOWER_ROT, mapFlat, pathPts, curve, PS, PB, pathDist,
  Hland, Hfar, landMask, heightCore, H, prof, cragR };

/* ================= the surface API (new; everything above is hers) ================= */
// Flat design space: x east, z south (the tower's crag C sits on the planet's +Y pole), y = altitude.
// mapFlat wraps it onto the sphere (azimuthal equidistant round C): 1 flat unit = 1 world unit along the ground.
const _p = new THREE.Vector3(), _q = new THREE.Vector3(), _e = new THREE.Vector3(), _s = new THREE.Vector3(), _n = new THREE.Vector3();
const _m = new THREE.Matrix4(), _qy = new THREE.Quaternion(), _Y = new THREE.Vector3(0, 1, 0);
export const MAX_RELIEF = 90;          // the terrain never rises above RP + 90 (the tower and crag are meshes)
export const CRAG_FOOT = 50;           // flat distance from C inside which the crag stands (prof[0] = 48)

// H(fx, fz): < 0 is water (its depth); the planet mesh draws max(h, 0), so the sea surface is at altitude 0
export function heightAtFlat(fx, fz) { return H(fx, fz); }
export function groundAtFlat(fx, fz) { return Math.max(0, H(fx, fz)); }
export function isWaterFlat(fx, fz) { return H(fx, fz) < 0; }
export function onCragFlat(fx, fz) { return Math.hypot(fx - C.x, fz - C.z) < CRAG_FOOT; }

export function flatToWorld(fx, y, fz, out = new THREE.Vector3()) { return mapFlat(fx, y, fz, out); }
// a point on the drawn ground (water at 0), lifted by `lift`
export function surfaceToWorld(fx, fz, lift = 0, out = new THREE.Vector3()) { return mapFlat(fx, groundAtFlat(fx, fz) + lift, fz, out); }
// the exact inverse of mapFlat (for points less than half a turn from C): -> { x, y, z } with y = altitude
export function worldToFlat(p, out = {}) {
  const r = Math.hypot(p.x, p.y, p.z), s = Math.hypot(p.x, p.z), th = Math.atan2(s, p.y), d = th * RP;
  const ux = s > 1e-12 ? p.x / s : 0, uz = s > 1e-12 ? p.z / s : 1;
  out.x = C.x + ux * d; out.y = r - RP; out.z = C.z + uz * d;
  return out;
}
// the radial up at a flat point (what upright things stand along)
export function upAtFlat(fx, fz, out = new THREE.Vector3()) { return mapFlat(fx, 0, fz, out).normalize(); }
// the drawn ground's normal (world space), by central differences on the wrapped surface
export function normalAtFlat(fx, fz, out = new THREE.Vector3(), e = 0.5) {
  surfaceToWorld(fx + e, fz, 0, _e).sub(surfaceToWorld(fx - e, fz, 0, _p));
  surfaceToWorld(fx, fz + e, 0, _s).sub(surfaceToWorld(fx, fz - e, 0, _q));
  return out.crossVectors(_s, _e).normalize();
}
// the local frame at a flat point: up = radial, east = flat +x, south = flat +z, orthonormal (right-handed:
// east, up, south = local x, y, z). position = the drawn ground + lift; quaternion turns an object built
// upright in flat space (y up, +x east, +z south) onto the planet; `yaw` = its rotation.y in flat space.
export function frameAt(fx, fz, { lift = 0, yaw = 0 } = {}) {
  const h = H(fx, fz), g = Math.max(0, h);
  const position = mapFlat(fx, g + lift, fz, new THREE.Vector3());
  const up = position.clone().normalize();
  const east = mapFlat(fx + 0.5, g, fz, new THREE.Vector3()).sub(mapFlat(fx - 0.5, g, fz, _p));
  east.addScaledVector(up, -east.dot(up)).normalize();
  const south = new THREE.Vector3().crossVectors(east, up).normalize();
  east.crossVectors(up, south);
  const quaternion = new THREE.Quaternion().setFromRotationMatrix(_m.makeBasis(east, up, south));
  if (yaw) quaternion.multiply(_qy.setFromAxisAngle(_Y, yaw));
  return { position, quaternion, up, east, south, height: h, ground: g, water: h < 0 };
}
export function placeOnSurface(obj, fx, fz, opts = {}) {
  const f = frameAt(fx, fz, opts);
  obj.position.copy(f.position); obj.quaternion.copy(f.quaternion);
  return f;
}
// her baking step for one geometry built in flat space (y up, ground at H): every vertex goes through mapFlat
// (reference lines 597-604). For decals that must follow the ground (fields, roads, marks) build them at H + a lift.
export function wrapFlatGeometry(geo, matrix = null) {
  if (matrix) geo.applyMatrix4(matrix);
  const p = geo.attributes.position;
  for (let i = 0; i < p.count; i++) { mapFlat(p.getX(i), p.getY(i), p.getZ(i), _n); p.setXYZ(i, _n.x, _n.y, _n.z); }
  p.needsUpdate = true; geo.computeVertexNormals(); geo.computeBoundingSphere();
  return geo;
}
// ray -> the drawn ground (march + bisection on the altitude gap). origin / dir in world space, dir unit.
// -> { fx, fz, world, height, onWater, t } | null
export function raycastSurface(origin, dir, maxAlt = MAX_RELIEF) {
  const R1 = RP + maxAlt, b = origin.dot(dir), c = origin.lengthSq() - R1 * R1, disc = b * b - c;
  if (disc < 0) return null;
  const sq = Math.sqrt(disc), tEnd = -b + sq;
  if (tEnd < 0) return null;
  const q = {};
  const gap = t => { _p.copy(origin).addScaledVector(dir, t); worldToFlat(_p, q); return q.y - Math.max(0, H(q.x, q.z)); };
  let t0 = Math.max(0, -b - sq), g0 = gap(t0), t1 = t0, hit = g0 <= 0;
  for (let i = 0; i < 4000 && !hit && t1 < tEnd; i++) {
    t1 = t0 + Math.max(0.2, g0 * 0.5);
    const g1 = gap(t1);
    if (g1 <= 0) { hit = true; break; }
    t0 = t1; g0 = g1;
  }
  if (!hit) return null;
  for (let i = 0; i < 28; i++) { const tm = (t0 + t1) / 2; if (gap(tm) > 0) t0 = tm; else t1 = tm; }
  const world = origin.clone().addScaledVector(dir, t1);
  worldToFlat(world, q);
  const height = H(q.x, q.z);
  return { fx: q.x, fz: q.z, world, height, onWater: height < 0, t: t1 };
}
