// Tower Planet chrome. Generated by tests/planet/extract.py from reference/the-tower-planet-clean.html.
// Her DOM controls (reference lines 959-1014): Walk the road / Back to orbit, Grain / Gouache, Colours, Space, Esc.
// The markup and CSS are hers, verbatim, in web/planet.html; this binds them to a planet (createPlanet).
// The game does not mount it (ART_DIRECTION §3).
import { COLOUR_KEYS, DEFAULT_COLOURS } from './materials.js';

export function mountPlanetUI(planet) {
const walkBtn=document.getElementById('walk'), backBtn=document.getElementById('back'), hint=document.getElementById('hint');
  planet.on('walking',v=>{walkBtn.setAttribute('aria-pressed',v);walkBtn.textContent=v?'Pause':(planet.mode==='walk'?'Keep walking':'Walk the road');});
  planet.on('mode',m=>{
    if(m==='walk'){backBtn.hidden=false;hint.textContent='Drag to look around';}
    else if(m==='orbit'){backBtn.hidden=true;hint.textContent='Drag to spin, scroll or pinch to zoom';}
    else backBtn.hidden=false;
  });
  const toWalk=planet.walk, toOrbit=planet.orbit, setWalking=planet.setWalking;
  walkBtn.addEventListener('click',()=>{ if(planet.mode==='orbit') toWalk(); else setWalking(!planet.walking); });
backBtn.addEventListener('click',toOrbit);
addEventListener('keydown',e=>{if(e.code==='Space'&&document.activeElement===document.body){e.preventDefault();walkBtn.click();}});

  const selectStyle=v=>planet.setBlend(v);
const styleButtons=[...document.querySelectorAll('#styles button')];
  function markStyle(selected){
  styleButtons.forEach(b=>{
    const checked=+b.dataset.mode===selected;
    b.setAttribute('aria-checked',checked);b.tabIndex=checked?0:-1;
  });
  }
  planet.on('style',markStyle); markStyle(planet.styleSelected);
styleButtons.forEach(b=>{
  b.addEventListener('click',()=>selectStyle(+b.dataset.mode));
  b.addEventListener('keydown',e=>{
    if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(e.key))return;
    e.preventDefault();
    const next=e.key==='Home'?0:e.key==='End'?1:1-(+b.dataset.mode);
    selectStyle(next);styleButtons[next].focus();
  });
});

  const UNI=planet.colourUniforms;
const pickers={}, cgrid=document.getElementById('cgrid');
  planet.on('colour',({k,hex})=>{
    if(pickers[k]) pickers[k].value=hex;
  if(k==='bg'){
    document.documentElement.style.setProperty('--bg',hex);
    const c=UNI.bg.value,l=.299*c.r+.587*c.g+.114*c.b;
    document.documentElement.style.setProperty('--hint',l>.55?'#12205e':'#f4eee0');
  }
  });
  const setColour=(k,hex)=>planet.setColour(k,hex);
for(const [k,label] of COLOUR_KEYS){
  const l=document.createElement('label');l.textContent=label;l.htmlFor='pk-'+k;
  const inp=document.createElement('input');inp.type='color';inp.id='pk-'+k;
  inp.addEventListener('input',()=>setColour(k,inp.value));
  pickers[k]=inp;cgrid.append(l,inp);setColour(k,planet.getColours()[k]);
}
const colBtn=document.getElementById('colBtn'),colPanel=document.getElementById('colours');
colBtn.addEventListener('click',()=>{const open=colPanel.hidden;colPanel.hidden=!open;colBtn.setAttribute('aria-pressed',open);});
addEventListener('keydown',e=>{if(e.key==='Escape'&&!colPanel.hidden){colPanel.hidden=true;colBtn.setAttribute('aria-pressed',false);colBtn.focus();}});
  return { walkBtn, backBtn, hint, styleButtons, pickers, colBtn, colPanel };
}
