// Tower Planet views. Generated by tests/planet/extract.py from reference/the-tower-planet-clean.html.
// Hers, verbatim: the orbit and road-walk cameras, computeFit / resize, drag / pinch / wheel input, the style
// state and the loop body with uBlend + DAYLIGHT by altitude (reference lines 913-957, 967-989, 1016-1092).
// New (documented hooks, docs/planet.md): mode 'local' (a camera over any flat point: cameraLocal) and mode
// 'path' (a flight from wherever the camera is down to a local view: descendTo), blend / daylight overrides,
// render hooks, pick and toScreen through her lens. In 'orbit' and 'walk' every line runs as in the reference.
import { smooth, lerp } from './context.js';
import { C, RP, TOWER_BASE, mapFlat, curve, H, worldToFlat, raycastSurface } from './terrain.js';

export function createViews(ctx, P, { input = true, emit = () => {} } = {}) {
  const { renderer, scene, camera, isMobile, reduceMotion, uTime, SUN, DAYLIGHT } = ctx;
  const { post, makeRT, renderFinish } = P;
/* ---------------- views ---------------- */
const U0=(()=>{let best=0,bd=1e9;for(let i=0;i<=400;i++){const p=curve.getPointAt(i/400);const d=Math.abs(p.z+1);if(d<bd){bd=d;best=i/400;}}return best;})();
const PATH_LEN=curve.getLength();
const ORBIT_TARGET=new THREE.Vector3(0,RP*0.16,0);
let orbitAz=0.12, orbitEl=0.52, orbitDist=RP*4, fitDist=RP*4;
function computeFit(){
  const a=innerWidth/innerHeight, v=THREE.MathUtils.degToRad(40), h=2*Math.atan(Math.tan(v/2)*a);
  const half=Math.min(v,h)/2;
  fitDist=(RP+110)/Math.sin(half)*(a<1?0.8:1.08);
}
function resize(){
  const w=innerWidth,h=innerHeight,pr=Math.min(devicePixelRatio||1,2);
  renderer.setPixelRatio(pr);renderer.setSize(w,h,false);
  const s=Math.max(pr,isMobile?1:1.5);
  const paintScale=Math.min(1,(isMobile?960:1440)/Math.max(w*s,h*s));
  makeRT(Math.round(w*s*paintScale),Math.round(h*s*paintScale));
  post.uniforms.uLine.value=Math.max(1,s*0.85);post.uniforms.uPR.value=pr;
  renderer.getDrawingBufferSize(post.uniforms.uOut.value);
  camera.aspect=w/h;camera.updateProjectionMatrix();
  const wasFit=Math.abs(orbitDist-fitDist)<1;
  computeFit(); if(wasFit||!started) orbitDist=fitDist;
}

/* ---------------- interaction ---------------- */
let mode='orbit', walking=false, journeyU=0, started=false, lastInteract=-1e9;
let yaw=0,pitch=0,yawT=0,pitchT=0;
const cv=renderer.domElement, pointers=new Map();
let pinchD=0;
  if (input) {
cv.addEventListener('pointerdown',e=>{pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});cv.setPointerCapture(e.pointerId);lastInteract=performance.now();
  if(pointers.size===2){const [a,b]=[...pointers.values()];pinchD=Math.hypot(a.x-b.x,a.y-b.y);}});
cv.addEventListener('pointermove',e=>{
  const p=pointers.get(e.pointerId); if(!p) return;
  const dx=e.clientX-p.x, dy=e.clientY-p.y; p.x=e.clientX; p.y=e.clientY; lastInteract=performance.now();
  if(pointers.size===2){
    const [a,b]=[...pointers.values()], d=Math.hypot(a.x-b.x,a.y-b.y);
    if(pinchD>0&&mode==='orbit') orbitDist=Math.max(RP*1.45,Math.min(RP*8,orbitDist*pinchD/d));
    pinchD=d; return;
  }
  if(mode==='orbit'){ orbitAz-=dx*.005; orbitEl=Math.max(-1.25,Math.min(1.35,orbitEl+dy*.004)); }
  else { yawT=Math.max(-.9,Math.min(.9,yawT+dx*.004)); pitchT=Math.max(-.35,Math.min(.35,pitchT+dy*.003)); }
});
const endPtr=e=>{pointers.delete(e.pointerId);pinchD=0;};
cv.addEventListener('pointerup',endPtr);cv.addEventListener('pointercancel',endPtr);
cv.addEventListener('wheel',e=>{e.preventDefault();lastInteract=performance.now();
  if(mode==='orbit') orbitDist=Math.max(RP*1.45,Math.min(RP*8,orbitDist*Math.exp(e.deltaY*0.0012)));},{passive:false});
  }

  // her setWalking / toWalk / toOrbit (959-962); their DOM halves moved to ui.js (emit)
  function setWalking(v){walking=v;emit('walking',v);}
  function toWalk(){followDescent=true;mode='walk';cancelPath();emit('mode',mode);setWalking(true);}
  function toOrbit(){followDescent=true;mode='orbit';cancelPath();emit('mode',mode);setWalking(false);yawT=pitchT=0;}

// A road journey restores the altitude transition; style buttons override it.
let followDescent=true, activeStyle=-1;
  function markStyle(){
  const selected=post.uniforms.uBlend.value>=.5?1:0;
  if(selected===activeStyle)return;
  activeStyle=selected;
    emit('style',selected);
  }
function selectStyle(style){followDescent=false;post.uniforms.uBlend.value=style;markStyle();}
markStyle();

/* ---------------- loop ---------------- */
let world;
const camPos=new THREE.Vector3(), camLook=new THREE.Vector3(), camUp=new THREE.Vector3(0,1,0);
const dPos=new THREE.Vector3(), dLook=new THREE.Vector3(), dUp=new THREE.Vector3();
const wW=new THREE.Vector3();
const cR=new THREE.Vector3(), cU=new THREE.Vector3(), cB=new THREE.Vector3(), L=new THREE.Vector3();
let last=performance.now(), snap=true, shadowWide=null;

  /* ---------------- new: local + path cameras, overrides, hooks ---------------- */
  let daylightOverride=null, localFov=50, pathFov=50, path=null;
  const local={fx:C.x, fz:0, dist:70, pitch:1.0, yaw:0, snap:false};
  const free={pos:new THREE.Vector3(0,RP*4,0), look:new THREE.Vector3(), up:new THREE.Vector3(0,0,-1), snap:false};
  const hooks={beforeRender:[], beforeFinish:[], afterFinish:[]};
  const _n=new THREE.Vector3(), _e=new THREE.Vector3(), _s=new THREE.Vector3(), _h=new THREE.Vector3(), _p=new THREE.Vector3();
  const pPos=new THREE.Vector3(), pLook=new THREE.Vector3(), pUp=new THREE.Vector3(), d0=new THREE.Vector3(), d1=new THREE.Vector3();
  const focus={fx:C.x, fz:0};
  const ground=(fx,fz)=>Math.max(0,H(fx,fz));
  const wrapAngle=a=>Math.atan2(Math.sin(a),Math.cos(a));
  // the local frame at a flat point: N radial up, E flat +x, S flat +z
  function frameVecs(fx,fz,y){
    mapFlat(fx,y,fz,_n).normalize();
    mapFlat(fx+.5,y,fz,_e).sub(mapFlat(fx-.5,y,fz,_p));
    _e.addScaledVector(_n,-_e.dot(_n)).normalize(); _s.crossVectors(_e,_n);
  }
  // a camera `dist` from the ground point (fx, fz), `pitch` above its horizon (pi/2 = straight down), on the
  // flat bearing `yaw` (0 = south of the point, looking north; +yaw swings it east). Up = the true camera up,
  // so a top-down view stays well defined. Never under the ground.
  function poseAt(fx,fz,dist,pitch,yaw,pos,look,up){
    const gy=ground(fx,fz);
    mapFlat(fx,gy,fz,look); frameVecs(fx,fz,gy);
    _h.copy(_e).multiplyScalar(Math.sin(yaw)).addScaledVector(_s,Math.cos(yaw));
    const cp=Math.cos(pitch), sp=Math.sin(pitch);
    pos.copy(look).addScaledVector(_h,dist*cp).addScaledVector(_n,dist*sp);
    up.copy(_n).multiplyScalar(cp).addScaledVector(_h,-sp).normalize();
    const q=worldToFlat(pos), floor=ground(q.x,q.z)+2.5;
    if(q.y<floor) mapFlat(q.x,floor,q.z,pos);
    focus.fx=fx; focus.fz=fz;
    return gy;
  }
  function cancelPath(){ if(path){ const p=path; path=null; p.resolve(false); } }
  // the start of a flight: the local view we are in, or (from orbit / walk) straight down over the point
  // under the camera, turned so the screen's up does not change
  function poseFromCamera(){
    if(mode==='local') return {...local};
    const f=worldToFlat(camPos), g=ground(f.x,f.z);
    frameVecs(f.x,f.z,g);
    _h.copy(camUp).addScaledVector(_n,-camUp.dot(_n));
    if(_h.lengthSq()<1e-8) _h.copy(_s).negate();
    _h.normalize().negate();
    return {fx:f.x, fz:f.z, dist:Math.max(1,camPos.length()-RP-g), pitch:Math.PI/2, yaw:Math.atan2(_h.dot(_e),_h.dot(_s))};
  }
  function placePath(now){
    const p=path;
    if(p.t0===null) p.t0=now;
    const s=Math.min(1,(now-p.t0)/p.ms);
    const a=p.from, b=p.to;
    // the focus slides across the globe early, the height falls on a log scale, the view stays top-down
    // until the last stretch, then tips into the target pitch
    const ef=smooth(0,.62,s), ed=smooth(.04,1,s);
    _p.copy(d0).lerp(d1,ef); if(p.arc>1e-6){ _p.copy(d0).multiplyScalar(Math.sin((1-ef)*p.arc)).addScaledVector(d1,Math.sin(ef*p.arc)).divideScalar(Math.sin(p.arc)); }
    const f=worldToFlat(_p.multiplyScalar(RP));
    const hop=Math.max(0,p.arc*RP*.55-Math.max(a.dist,b.dist))*Math.sin(Math.PI*Math.min(1,s/.8));
    const dist=Math.exp(lerp(Math.log(a.dist),Math.log(b.dist),ed))+hop;
    const pitch=lerp(lerp(a.pitch,Math.PI/2,smooth(0,.25,s)),b.pitch,smooth(.58,1,s));
    const yaw=a.yaw+wrapAngle(b.yaw-a.yaw)*smooth(.12,.9,s);
    pathFov=lerp(p.fov0,localFov,smooth(.3,1,s));   // the lens widens as we come down, not before
    poseAt(f.x,f.z,dist,pitch,yaw,dPos,dLook,dUp);
    // ease out of the camera we started from
    const w=smooth(0,.3,s);
    dPos.lerp(p.P0,1-w); dLook.lerp(p.L0,1-w); dUp.lerp(p.U0,1-w).normalize();
    if(s>=1){
      Object.assign(local,b); mode='local'; path=null; emit('mode',mode); p.resolve(true);
    }
  }
  function descendTo(o={}){
    cancelPath();
    const a=poseFromCamera();
    const pitch=o.pitch??1.05;
    const dist=o.dist??(o.alt!=null?o.alt/Math.max(.2,Math.sin(pitch)):70);
    const b={fx:o.fx??local.fx, fz:o.fz??local.fz, dist, pitch, yaw:o.yaw??local.yaw};
    if(o.fov!=null) localFov=o.fov;
    if(walking) setWalking(false);
    mapFlat(a.fx,0,a.fz,d0).normalize(); mapFlat(b.fx,0,b.fz,d1).normalize();
    return new Promise(resolve=>{
      path={from:a, to:b, ms:Math.max(1,o.ms??5200), t0:null, arc:Math.acos(Math.max(-1,Math.min(1,d0.dot(d1)))),
        P0:camPos.clone(), L0:camLook.clone(), U0:camUp.clone(), fov0:camera.fov, resolve};
      mode='path'; emit('mode',mode);
    });
  }
  // a camera the host places itself (the voyage to the Moon, cut scenes): world-space position / look / up.
  // Her smoothing still applies unless snap; blend + daylight still follow the altitude.
  function cameraFree(o={}){
    cancelPath();
    if(o.position) free.pos.copy(o.position); if(o.look) free.look.copy(o.look); if(o.up) free.up.copy(o.up);
    if(o.fov!=null) localFov=o.fov;
    free.snap=!!o.snap;
    if(walking) setWalking(false);
    if(mode!=='free'){ mode='free'; emit('mode',mode); }
  }
  function cameraLocal(o={}){
    cancelPath();
    for(const k of ['fx','fz','dist','pitch','yaw']) if(o[k]!=null) local[k]=o[k];
    if(o.fov!=null) localFov=o.fov;
    local.snap=!!o.snap;
    if(walking) setWalking(false);
    if(mode!=='local'){ mode='local'; emit('mode',mode); }
    return {...local};
  }

  // her frame() body (lines 1024-1092): the loop itself (requestAnimationFrame) lives in planet.js
  function frame(now){
  const dt=Math.min(.05,(now-last)/1000);last=now;
  uTime.value+=reduceMotion?dt*.2:dt;

  /* camera journey along the road */
  if(walking){
    journeyU+=dt*1.55/PATH_LEN;
    if(U0+journeyU>=0.985){ journeyU=0; toOrbit(); }
  }
  const u=Math.min(U0+journeyU,.985);
  let wp=curve.getPointAt(u), tan=curve.getTangentAt(u), wy=H(wp.x,wp.z);
  mapFlat(wp.x,wy,wp.z,wW);

  /* camera targets */
  if(mode==='orbit'){
    if(now-lastInteract>3500 && !reduceMotion) orbitAz+=dt*0.035;
    dPos.set(Math.cos(orbitEl)*Math.sin(orbitAz),Math.sin(orbitEl),Math.cos(orbitEl)*Math.cos(orbitAz)).multiplyScalar(orbitDist).add(ORBIT_TARGET);
    dLook.copy(ORBIT_TARGET); dUp.set(0,1,0);
  } else if(mode==='local'||mode==='path'||mode==='free'){
    if(mode==='free'){ dPos.copy(free.pos); dLook.copy(free.look); dUp.copy(free.up).normalize(); const q=worldToFlat(free.look); focus.fx=q.x; focus.fz=q.z; if(free.snap){ snap=true; free.snap=false; } }
    if(mode==='path') placePath(now);
    if(mode==='local'){ poseAt(local.fx,local.fz,local.dist,local.pitch,local.yaw,dPos,dLook,dUp); if(local.snap){ snap=true; local.snap=false; } }
    else if(mode==='path') snap=true;
    wy=ground(focus.fx,focus.fz); mapFlat(focus.fx,wy,focus.fz,wW);
  } else {
    const bx=wp.x-tan.x*15, bz=wp.z-tan.z*15;
    mapFlat(bx,Math.max(wy+5.2,H(bx,bz)+3.5),bz,dPos);
    const lx=lerp(wp.x+tan.x*30,C.x,.55), lz=lerp(wp.z+tan.z*30,C.z,.55), ly=lerp(wy+6,TOWER_BASE+22,.55);
    mapFlat(lx,ly,lz,dLook);
    dUp.copy(dPos).normalize();
  }
  const k=snap?1:1-Math.exp(-dt*1.8);
  camPos.lerp(dPos,k); camLook.lerp(dLook,k); camUp.lerp(dUp,k).normalize();
  // never fly through the ground on the way between views
  const minR=RP+Math.max(3, Math.min(60, camPos.distanceTo(dPos)*0.4));
  if(camPos.length()<minR) camPos.setLength(minR);
  snap=false;
  camera.position.copy(camPos); camera.up.copy(camUp); camera.lookAt(camLook);
  const fovT=mode==='orbit'?40:mode==='walk'?68:mode==='path'?pathFov:localFov; camera.fov+= (fovT-camera.fov)*(1-Math.exp(-dt*2)); camera.updateProjectionMatrix();
  if(mode==='walk'){
    if(pointers.size===0){yawT*=Math.exp(-dt*.9);pitchT*=Math.exp(-dt*.9);}
    const kk=1-Math.exp(-dt*6); yaw+=(yawT-yaw)*kk; pitch+=(pitchT-pitch)*kk;
  } else { yaw*=.9; pitch*=.9; }
  camera.rotateY(-yaw); camera.rotateX(-pitch);
  camera.updateMatrixWorld();

  /* sun from the viewer's upper-left-front */
  cR.setFromMatrixColumn(camera.matrixWorld,0); cU.setFromMatrixColumn(camera.matrixWorld,1); cB.setFromMatrixColumn(camera.matrixWorld,2);
  L.copy(cR).multiplyScalar(-.55).addScaledVector(cU,.62).addScaledVector(cB,.52).normalize();
  SUN.copy(L);
  const sun=world.sun, sc=sun.shadow.camera, wide=(mode==='orbit'||((mode==='path'||mode==='free')&&camPos.length()-RP>220));
  if(wide){ world.sunTarget.position.set(0,0,0); sun.position.copy(L).multiplyScalar(700); }
  else { world.sunTarget.position.copy(wW); sun.position.copy(wW).addScaledVector(L,320); }
  if(shadowWide!==wide){
    shadowWide=wide;
    if(wide) Object.assign(sc,{left:-300,right:300,top:300,bottom:-300,near:150,far:1300});
    else Object.assign(sc,{left:-110,right:110,top:110,bottom:-110,near:10,far:700});
    sc.updateProjectionMatrix();
  }
  world.sunTarget.updateMatrixWorld();

  // Daylight follows altitude independently of the selected paint style.
  const altitude=Math.max(0,camera.position.length()-RP);
  DAYLIGHT.value=smooth(190,Math.max(32,wy+20),altitude);
  if(daylightOverride!==null) DAYLIGHT.value=daylightOverride;
  // Blend from the actual camera altitude, so descending, pausing and returning all stay continuous.
  if(followDescent){
    const paintStarts=Math.max(240,(fitDist-RP)*.86),paintFull=Math.max(24,wy+20);
    post.uniforms.uBlend.value=smooth(paintStarts,paintFull,altitude);
    markStyle();
  }
  world.sky.position.copy(camera.position);
  world.clouds.rotation.y+=dt*(reduceMotion?0.0005:0.004);

  for(const fn of hooks.beforeRender) fn(dt,now);
  const rt=P.rt;
  renderer.setRenderTarget(rt);renderer.render(scene,camera);
  for(const fn of hooks.beforeFinish) fn(dt,now);
  renderFinish();
  for(const fn of hooks.afterFinish) fn(dt,now);
  }

  /* ---------------- pick / toScreen through her lens (post: fish, uFish) ---------------- */
  const ray=new THREE.Raycaster(), ndc=new THREE.Vector2();
  function fishUV(x,y){
    const o=post.uniforms.uOut.value, a=o.x/o.y, F=post.uniforms.uFish.value;
    let px=(x-.5)*a, py=y-.5; const k=1/(1+F*(px*px+py*py)); px*=k; py*=k;
    return [px/a+.5, py+.5];
  }
  // screen point -> the planet's ground under it: { fx, fz, world, height, onWater } | null
  function pick(clientX,clientY){
    const r=renderer.domElement.getBoundingClientRect();
    const [sx,sy]=fishUV((clientX-r.left)/r.width,1-(clientY-r.top)/r.height);
    ndc.set(sx*2-1,sy*2-1); ray.setFromCamera(ndc,camera);
    return raycastSurface(ray.ray.origin,ray.ray.direction);
  }
  // world point -> client pixels on the lensed screen: { x, y, behind }
  function toScreen(v){
    _p.copy(v).project(camera);
    const tx=(_p.x+1)/2, ty=(_p.y+1)/2; let x=tx, y=ty;
    for(let i=0;i<12;i++){ const [fx,fy]=fishUV(x,y); x+=tx-fx; y+=ty-fy; }
    const r=renderer.domElement.getBoundingClientRect();
    return { x:r.left+x*r.width, y:r.top+(1-y)*r.height, behind:_p.z>1 };
  }

  return {
    frame, resize, computeFit, pick, toScreen, hooks,
    prime(t){ last=t; }, setWorld(w){ world=w; }, markStarted(){ started=true; },
    walk:toWalk, orbit:toOrbit, setWalking, descendTo, cameraLocal, cameraFree,
    setBlend:selectStyle,
    autoBlend(on=true){ followDescent=!!on; if(on) markStyle(); },
    setDaylight(v){ daylightOverride=v; },
    autoDaylight(on=true){ daylightOverride=on?null:DAYLIGHT.value; },
    orbitSpin(on=true){ lastInteract=on?-1e9:Infinity; },
    setOrbit(o={}){ if(o.az!=null) orbitAz=o.az; if(o.el!=null) orbitEl=o.el; if(o.dist!=null) orbitDist=o.dist; },
    get mode(){ return mode; }, get walking(){ return walking; }, get styleSelected(){ return activeStyle; },
    get followDescent(){ return followDescent; }, get local(){ return {...local}; }, get focus(){ return {...focus}; },
    get altitude(){ return Math.max(0,camera.position.length()-RP); },
    state(){ return { mode, walking, blend:post.uniforms.uBlend.value, daylight:DAYLIGHT.value, followDescent,
      daylightOverride, altitude:Math.max(0,camera.position.length()-RP), orbit:{az:orbitAz, el:orbitEl, dist:orbitDist, fitDist},
      local:{...local}, focus:{...focus}, fov:camera.fov, path:path?{from:path.from, to:path.to, ms:path.ms}:null }; }
  };
}
